INSERT INTO disease (id, disease) VALUES (2, 'Поверхностная травма головы');
INSERT INTO disease (id, disease) VALUES (3, 'Открытая рана головы');
INSERT INTO disease (id, disease) VALUES (4, 'Перелом черепа и лицевых костей');
INSERT INTO disease (id, disease) VALUES (5, 'Вывих, растяжение и перенапряжение суставов и связок головы');
INSERT INTO disease (id, disease) VALUES (6, 'Травма черепных нервов');
INSERT INTO disease (id, disease) VALUES (7, 'Травма глаза и глазницы');
INSERT INTO disease (id, disease) VALUES (8, 'Внутричерепная травма');
INSERT INTO disease (id, disease) VALUES (9, 'Размозжение головы');
INSERT INTO disease (id, disease) VALUES (10, 'Травматическая ампутация части головы');
INSERT INTO disease (id, disease) VALUES (11, 'Другие и неуточненные травмы головы');
INSERT INTO disease (id, disease) VALUES (12, 'Поверхностная травма шеи');
INSERT INTO disease (id, disease) VALUES (13, 'Открытая рана шеи');
INSERT INTO disease (id, disease) VALUES (14, 'Перелом шейного отдела позвоночника');
INSERT INTO disease (id, disease) VALUES (15, 'Вывих, растяжение и перенапряжение капсульно-связочного аппарата на уровне шеи');
INSERT INTO disease (id, disease) VALUES (16, 'Травма нервов и спинного мозга на уровне шеи');
INSERT INTO disease (id, disease) VALUES (17, 'Травма кровеносных сосудов на уровне шеи');
INSERT INTO disease (id, disease) VALUES (18, 'Травма мышц и сухожилий на уровне шеи');
INSERT INTO disease (id, disease) VALUES (19, 'Размозжение шеи');
INSERT INTO disease (id, disease) VALUES (20, 'Травматическая ампутация на уровне шеи');
INSERT INTO disease (id, disease) VALUES (21, 'Другие и неуточненные травмы шеи');
INSERT INTO disease (id, disease) VALUES (22, 'Поверхностная травма грудной клетки');
INSERT INTO disease (id, disease) VALUES (23, 'Открытая рана грудной клетки');
INSERT INTO disease (id, disease) VALUES (24, 'Перелом ребра (ребер), грудины и грудного отдела позвоночника');
INSERT INTO disease (id, disease) VALUES (25, 'Вывих, растяжение и перенапряжение капсульно-связочного аппарата грудной клетки');
INSERT INTO disease (id, disease) VALUES (26, 'Травма нервов и спинного мозга в грудном отделе');
INSERT INTO disease (id, disease) VALUES (27, 'Травма кровеносных сосудов грудного отдела');
INSERT INTO disease (id, disease) VALUES (28, 'Травма сердца');
INSERT INTO disease (id, disease) VALUES (29, 'Травма других и неуточненных органов грудной полости');
INSERT INTO disease (id, disease) VALUES (30, 'Размозжение грудной клетки и травматическая ампутация части грудной клетки');
INSERT INTO disease (id, disease) VALUES (31, 'Другие и неуточненные травмы грудной клетки');
INSERT INTO disease (id, disease) VALUES (32, 'Поверхностная травма живота, нижней части спины и таза');
INSERT INTO disease (id, disease) VALUES (33, 'Открытая рана живота, нижней части спины и таза');
INSERT INTO disease (id, disease) VALUES (34, 'Перелом пояснично-крестцового отдела позвоночника и костей таза');
INSERT INTO disease (id, disease) VALUES (35, 'Вывих, растяжение и перенапряжение капсульно-связочного аппарата поясничного отдела позвоночника и таза');
INSERT INTO disease (id, disease) VALUES (36, 'Травма нервов и поясничного отдела спинного мозга на уровне живота, нижней части спины и таза');
INSERT INTO disease (id, disease) VALUES (37, 'Травма кровеносных сосудов на уровне живота, нижней части спины и таза');
INSERT INTO disease (id, disease) VALUES (38, 'Травма органов брюшной полости');
INSERT INTO disease (id, disease) VALUES (39, 'Травма тазовых органов');
INSERT INTO disease (id, disease) VALUES (40, 'Размозжение и травматическая ампутация части живота, нижней части спины и таза');
INSERT INTO disease (id, disease) VALUES (41, 'Другие и неуточненные травмы живота, нижней части спины и таза');
INSERT INTO disease (id, disease) VALUES (42, 'Поверхностная травма плечевого пояса и плеча');
INSERT INTO disease (id, disease) VALUES (43, 'Открытая рана плечевого пояса и плеча');
INSERT INTO disease (id, disease) VALUES (44, 'Перелом на уровне плечевого пояса и плеча');
INSERT INTO disease (id, disease) VALUES (45, 'Вывих, растяжение и перенапряжение капсульно-связочного аппарата плечевого пояса');
INSERT INTO disease (id, disease) VALUES (46, 'Травма нервов на уровне плечевого пояса и плеча');
INSERT INTO disease (id, disease) VALUES (47, 'Травма кровеносных сосудов на уровне плечевого пояса и плеча');
INSERT INTO disease (id, disease) VALUES (48, 'Травма мышцы и сухожилия на уровне плечевого пояса и плеча');
INSERT INTO disease (id, disease) VALUES (49, 'Размозжение плечевого пояса и плеча');
INSERT INTO disease (id, disease) VALUES (50, 'Травматическая ампутация плечевого пояса и плеча');
INSERT INTO disease (id, disease) VALUES (51, 'Другие и неуточненные травмы плечевого пояса и плеча');
INSERT INTO disease (id, disease) VALUES (52, 'Поверхностная травма предплечья');
INSERT INTO disease (id, disease) VALUES (53, 'Открытая рана предплечья');
INSERT INTO disease (id, disease) VALUES (54, 'Перелом костей предплечья');
INSERT INTO disease (id, disease) VALUES (55, 'Вывих, растяжение и перенапряжение капсульно-связочного аппарата локтевого сустава');
INSERT INTO disease (id, disease) VALUES (56, 'Травма нервов на уровне предплечья');
INSERT INTO disease (id, disease) VALUES (57, 'Травма кровеносных сосудов на уровне предплечья');
INSERT INTO disease (id, disease) VALUES (58, 'Травма мышцы и сухожилия на уровне предплечья');
INSERT INTO disease (id, disease) VALUES (59, 'Размозжение предплечья');
INSERT INTO disease (id, disease) VALUES (60, 'Травматическая ампутация предплечья');
INSERT INTO disease (id, disease) VALUES (61, 'Другие и неуточненные травмы предплечья');
INSERT INTO disease (id, disease) VALUES (62, 'Поверхностная травма запястья и кисти');
INSERT INTO disease (id, disease) VALUES (63, 'Открытая рана запястья и кисти');
INSERT INTO disease (id, disease) VALUES (64, 'Перелом на уровне запястья и кисти');
INSERT INTO disease (id, disease) VALUES (65, 'Вывих, растяжение и перенапряжение капсульно-связочного аппарата на уровне запястья и кисти');
INSERT INTO disease (id, disease) VALUES (66, 'Травма нервов на уровне запястья и кисти');
INSERT INTO disease (id, disease) VALUES (67, 'Травма кровеносных сосудов на уровне запястья и кисти');
INSERT INTO disease (id, disease) VALUES (68, 'Травма мышцы и сухожилия на уровне запястья и кисти');
INSERT INTO disease (id, disease) VALUES (69, 'Размозжение запястья и кисти');
INSERT INTO disease (id, disease) VALUES (70, 'Травматическая ампутация запястья и кисти');
INSERT INTO disease (id, disease) VALUES (71, 'Другие и неуточненные травмы запястья и кисти');
INSERT INTO disease (id, disease) VALUES (72, 'Поверхностная травма области тазобедренного сустава и бедра');
INSERT INTO disease (id, disease) VALUES (73, 'Открытая рана области тазобедренного сустава и бедра');
INSERT INTO disease (id, disease) VALUES (74, 'Перелом бедренной кости');
INSERT INTO disease (id, disease) VALUES (75, 'Вывих, растяжение и перенапряжение капсульно-связочного');
INSERT INTO disease (id, disease) VALUES (76, 'Травмы нервов на уровне тазобедренного сустава бедра');
INSERT INTO disease (id, disease) VALUES (77, 'Травма кровеносных сосудов на уровне тазобедренного сустава и бедра');
INSERT INTO disease (id, disease) VALUES (78, 'Травма мышцы и сухожилия на уровне тазобедренного сустава и бедра');
INSERT INTO disease (id, disease) VALUES (79, 'Размозжение области тазобедренного сустава и бедра');
INSERT INTO disease (id, disease) VALUES (80, 'Травматическая ампутация области тазобедренного сустава и бедра');
INSERT INTO disease (id, disease) VALUES (81, 'Другие и неуточненные травмы области тазобедренного сустава и бедра');
INSERT INTO disease (id, disease) VALUES (82, 'Поверхностная травма голени');
INSERT INTO disease (id, disease) VALUES (83, 'Открытая рана голени');
INSERT INTO disease (id, disease) VALUES (84, 'Перелом голени, включая голеностопный сустав');
INSERT INTO disease (id, disease) VALUES (85, 'Вывих, растяжение и перенапряжение капсульно-связочного аппарата коленного сустава');
INSERT INTO disease (id, disease) VALUES (86, 'Травма нервов на уровне голени');
INSERT INTO disease (id, disease) VALUES (87, 'Травма кровеносных сосудов на уровне голени');
INSERT INTO disease (id, disease) VALUES (88, 'Травма мышцы и сухожилия на уровне голени');
INSERT INTO disease (id, disease) VALUES (89, 'Размозжение голени');
INSERT INTO disease (id, disease) VALUES (90, 'Травматическая ампутация голени');
INSERT INTO disease (id, disease) VALUES (91, 'Другие и неуточненные травмы голени');
INSERT INTO disease (id, disease) VALUES (92, 'Поверхностная травма области голеностопного сустава и стопы');
INSERT INTO disease (id, disease) VALUES (93, 'Открытая рана области голеностопного сустава и стопы');
INSERT INTO disease (id, disease) VALUES (94, 'Перелом стопы, исключая перелом голеностопного сустава');
INSERT INTO disease (id, disease) VALUES (95, 'Вывих, растяжение и перенапряжение капсульно-связочного аппарата голеностопного сустава и стопы');
INSERT INTO disease (id, disease) VALUES (96, 'Травма нервов на уровне голеностопного сустава и стопы');
INSERT INTO disease (id, disease) VALUES (97, 'Травма кровеносных сосудов на уровне голеностопного сустава и стопы');
INSERT INTO disease (id, disease) VALUES (98, 'Травма мышцы и сухожилия на уровне голеностопного сустава и стопы');
INSERT INTO disease (id, disease) VALUES (99, 'Размозжение голеностопного сустава и стопы');
INSERT INTO disease (id, disease) VALUES (100, 'Травматическая ампутация на уровне голеностопного сустава и стопы');
INSERT INTO disease (id, disease) VALUES (101, 'Другие и неуточненные травмы голеностопного сустава и стопы');
INSERT INTO disease (id, disease) VALUES (102, 'Поверхностные травмы, захватывающие несколько областей тела');
INSERT INTO disease (id, disease) VALUES (103, 'Открытые раны, захватывающие несколько областей тела');
INSERT INTO disease (id, disease) VALUES (104, 'Переломы, захватывающие несколько областей тела');
INSERT INTO disease (id, disease) VALUES (105, 'Вывихи, растяжения и перенапряжение капсульно-связочного аппарата суставов, захватывающие несколько областей тела');
INSERT INTO disease (id, disease) VALUES (106, 'Размозжения, захватывающие несколько областей тела');
INSERT INTO disease (id, disease) VALUES (107, 'Травматические ампутации, захватывающие несколько областей тела');
INSERT INTO disease (id, disease) VALUES (108, 'Другие травмы, охватывающие несколько областей тела, не классифицированные в других рубриках');
INSERT INTO disease (id, disease) VALUES (109, 'Множественные травмы неуточненные');
INSERT INTO disease (id, disease) VALUES (110, 'Перелом позвоночника на неуточненном уровне');
INSERT INTO disease (id, disease) VALUES (111, 'Другие травмы позвоночника и туловища на неуточненном уровне');
INSERT INTO disease (id, disease) VALUES (112, 'Перелом верхней конечности на неуточненном уровне');
INSERT INTO disease (id, disease) VALUES (113, 'Другие травмы верхней конечности на неуточненном уровне');
INSERT INTO disease (id, disease) VALUES (114, 'Перелом нижней конечности на неуточненном уровне');
INSERT INTO disease (id, disease) VALUES (115, 'Другие травмы нижней конечности на неуточненном уровне');
INSERT INTO disease (id, disease) VALUES (116, 'Травма неуточненной локализации');
INSERT INTO disease (id, disease) VALUES (117, 'Инородное тело в наружной части глаза');
INSERT INTO disease (id, disease) VALUES (118, 'Инородное тело в ухе');
INSERT INTO disease (id, disease) VALUES (119, 'Инородное тело в дыхательных путях');
INSERT INTO disease (id, disease) VALUES (120, 'Инородное тело в пищеварительном тракте');
INSERT INTO disease (id, disease) VALUES (121, 'Инородное тело в мочеполовых путях');
INSERT INTO disease (id, disease) VALUES (122, 'ТЕРМИЧЕСКИЕ И ХИМИЧЕСКИЕ ОЖОГИ НАРУЖНЫХ ПОВЕРХНОСТЕЙ ТЕЛА, УТОЧНЕННЫЕ ПО ИХ ЛОКАЛИЗАЦИИ');
INSERT INTO disease (id, disease) VALUES (123, 'Термические и химические ожоги головы и шеи');
INSERT INTO disease (id, disease) VALUES (124, 'Термические и химические ожоги туловища');
INSERT INTO disease (id, disease) VALUES (125, 'Термические и химические ожоги области плечевого пояса и верхней конечности, исключая запястье и кисть');
INSERT INTO disease (id, disease) VALUES (126, 'Термические и химические ожоги запястья и кисти');
INSERT INTO disease (id, disease) VALUES (127, 'Термические и химические ожоги области тазобедренного сустава и нижней конечности, исключая голеностопный сустав и стопу');
INSERT INTO disease (id, disease) VALUES (128, 'Термические и химические ожоги области голеностопного сустава и стопы');
INSERT INTO disease (id, disease) VALUES (129, 'ТЕРМИЧЕСКИЕ И ХИМИЧЕСКИЕ ОЖОГИ ГЛАЗА И ВНУТРЕННИХ ОРГАНОВ');
INSERT INTO disease (id, disease) VALUES (130, 'Термические и химические ожоги,  ограниченные областью глаза и его придаточного аппарата');
INSERT INTO disease (id, disease) VALUES (131, 'Термические и химические ожоги дыхательных путей');
INSERT INTO disease (id, disease) VALUES (132, 'Термические и химические ожоги других внутренних органов');
INSERT INTO disease (id, disease) VALUES (133, 'ТЕРМИЧЕСКИЕ И ХИМИЧЕСКИЕ ОЖОГИ МНОЖЕСТВЕННОЙ И НЕУТОЧНЕННОЙ ЛОКАЛИЗАЦИИ');
INSERT INTO disease (id, disease) VALUES (134, 'Термические и химические ожоги нескольких областей тела');
INSERT INTO disease (id, disease) VALUES (135, 'Термические и химические ожоги неуточненной локализации');
INSERT INTO disease (id, disease) VALUES (136, 'Термические ожоги, классифицированные в зависимости от площади пораженной поверхности тела');
INSERT INTO disease (id, disease) VALUES (137, 'Химические ожоги, классифицированные в зависимости от площади пораженной поверхности тела');
INSERT INTO disease (id, disease) VALUES (138, 'Поверхностное отморожение');
INSERT INTO disease (id, disease) VALUES (139, 'Отморожение с некрозом тканей');
INSERT INTO disease (id, disease) VALUES (140, 'Отморожение, захватывающее несколько областей тела, и неуточненное отморожение');
INSERT INTO disease (id, disease) VALUES (141, 'Отравление антибиотиками системного действия');
INSERT INTO disease (id, disease) VALUES (142, 'Отравление другими противоинфекционными и противопаразитарными средствами системного действия');
INSERT INTO disease (id, disease) VALUES (143, 'Отравление гормонами, их синтетическими заменителями и антагонистами, не классифицированное в других рубриках');
INSERT INTO disease (id, disease) VALUES (144, 'Отравление неопиоидными анальгезирующими, жаропонижающими и противоревматическими средствами');
INSERT INTO disease (id, disease) VALUES (145, 'Отравление наркотиками и психодислептиками [галлюциногенами]');
INSERT INTO disease (id, disease) VALUES (146, 'Отравление анестезирующими средствами и терапевтическими газами');
INSERT INTO disease (id, disease) VALUES (147, 'Отравление противосудорожными, седативными, снотворными и противопаркинсоническими средствами');
INSERT INTO disease (id, disease) VALUES (148, 'Отравление психотропными средствами, не классифицированное в других рубриках');
INSERT INTO disease (id, disease) VALUES (149, 'Отравление препаратами, действующими преимущественно на вегетативную нервную систему');
INSERT INTO disease (id, disease) VALUES (150, 'Отравление препаратами, преимущественно системного действия и гематологическими агентами, не классифицированное в других рубриках');
INSERT INTO disease (id, disease) VALUES (151, 'Отравление препаратами, действующими преимущественно на сердечно-сосудистую систему');
INSERT INTO disease (id, disease) VALUES (152, 'Отравление препаратами, действующими преимущественно на органы пищеварения');
INSERT INTO disease (id, disease) VALUES (153, 'Отравление препаратами, действующими преимущественно на гладкую и скелетную мускулатуру и органы дыхания');
INSERT INTO disease (id, disease) VALUES (154, 'Отравление препаратами местного действия, влияющими преимущественно на кожу и слизистые оболочки, и средствами, используемыми в офтальмологической, отоларингологической и стоматологической практике');
INSERT INTO disease (id, disease) VALUES (155, 'Отравление диуретиками и другими неуточненными лекарственными средствами, медикаментами и биологическими веществами');
INSERT INTO disease (id, disease) VALUES (156, 'Токсическое действие алкоголя');
INSERT INTO disease (id, disease) VALUES (157, 'Токсическое действие органических растворителей');
INSERT INTO disease (id, disease) VALUES (158, 'Токсическое действие галогенпроизводных алифатических и ароматических углеводородов');
INSERT INTO disease (id, disease) VALUES (159, 'Токсическое действие разъедающих веществ');
INSERT INTO disease (id, disease) VALUES (160, 'Токсическое действие мыл и детергентов');
INSERT INTO disease (id, disease) VALUES (161, 'Токсическое действие металлов');
INSERT INTO disease (id, disease) VALUES (162, 'Токсическое действие других неорганических веществ');
INSERT INTO disease (id, disease) VALUES (163, 'Токсическое действие окиси углерода');
INSERT INTO disease (id, disease) VALUES (164, 'Токсическое действие других газов, дымов и паров');
INSERT INTO disease (id, disease) VALUES (165, 'Токсическое действие пестицидов');
INSERT INTO disease (id, disease) VALUES (166, 'Токсическое действие ядовитых веществ, содержащихся в съеденных пищевых морепродуктах');
INSERT INTO disease (id, disease) VALUES (167, 'Токсическое действие других ядовитых веществ, содержащихся в съеденных пищевых продуктах');
INSERT INTO disease (id, disease) VALUES (168, 'Токсический эффект, обусловленный контактом с ядовитыми животными');
INSERT INTO disease (id, disease) VALUES (169, 'Токсическое действие загрязняющих пищевые прдукты афлатоксина и других микотоксинов');
INSERT INTO disease (id, disease) VALUES (170, 'Токсическое действие других и неуточненных веществ');
INSERT INTO disease (id, disease) VALUES (171, 'Неуточненные эффекты излучения');
INSERT INTO disease (id, disease) VALUES (172, 'Эффекты воздействия высокой температуры и света');
INSERT INTO disease (id, disease) VALUES (173, 'Гипотермия');
INSERT INTO disease (id, disease) VALUES (174, 'Другие эффекты воздействия низкой температуры');
INSERT INTO disease (id, disease) VALUES (175, 'Воздействие атмосферного давления и давления воды');
INSERT INTO disease (id, disease) VALUES (176, 'Асфиксия');
INSERT INTO disease (id, disease) VALUES (177, 'Проявление других форм неблагоприятного воздействия [депривации]');
INSERT INTO disease (id, disease) VALUES (178, 'Синдром жестокого обращения');
INSERT INTO disease (id, disease) VALUES (179, 'Воздействие других внешних причин');
INSERT INTO disease (id, disease) VALUES (180, 'Неблагоприятные эффекты, не классифицированные в других рубриках');
INSERT INTO disease (id, disease) VALUES (181, 'Осложнения, связанные с инфузией, трансфузией и лечебной инъекцией');
INSERT INTO disease (id, disease) VALUES (182, 'Осложнения процедур, не классифицированные в других рубриках');
INSERT INTO disease (id, disease) VALUES (183, 'Осложнения, связанные с сердечными и сосудистыми устройствами, имплантатами и трансплантатами');
INSERT INTO disease (id, disease) VALUES (184, 'Осложнения, связанные с мочеполовыми протезными устройствами,    имплантатами и трансплантатами');
INSERT INTO disease (id, disease) VALUES (185, 'Осложнения, связанные с внутренними ортопедическими протезными устройствами, имплантатами и трансплантатами');
INSERT INTO disease (id, disease) VALUES (186, 'Осложнения, связанные с внутренними протезными устройствами, имплантатами и трансплантатами');
INSERT INTO disease (id, disease) VALUES (187, 'Отмирание и отторжение пересаженных органов и тканей');
INSERT INTO disease (id, disease) VALUES (188, 'Осложнения, характерные для реплантации и ампутации');
INSERT INTO disease (id, disease) VALUES (189, 'Другие осложнения хирургических и терапевтических вмешательств, не классифицированные в других рубриках');
INSERT INTO disease (id, disease) VALUES (190, 'Последствия травм головы');
INSERT INTO disease (id, disease) VALUES (191, 'Последствия травм шеи и туловища');
INSERT INTO disease (id, disease) VALUES (192, 'Последствия травм верхней конечности');
INSERT INTO disease (id, disease) VALUES (193, 'Последствия травм нижней конечности');
INSERT INTO disease (id, disease) VALUES (194, 'Последствия травм, захватывающих несколько областей тела, и травм неуточненной локализации');
INSERT INTO disease (id, disease) VALUES (195, 'Последствия термических и химических ожогов и отморожений');
INSERT INTO disease (id, disease) VALUES (196, 'Последствия отравлений лекарственными средствами, медикаментами и биологическими веществами');
INSERT INTO disease (id, disease) VALUES (197, 'Последствия токсического действия веществ преимущественно немедицинского назначения');
INSERT INTO disease (id, disease) VALUES (198, 'Последствия других и неуточненных воздействий внешних причин');