INSERT INTO infection (id, infection) VALUES (1, 'Холера');
INSERT INTO infection (id, infection) VALUES (2, 'Тиф и паратиф');
INSERT INTO infection (id, infection) VALUES (3, 'Другие сальмонеллезные инфекции');
INSERT INTO infection (id, infection) VALUES (4, 'Шигеллез');
INSERT INTO infection (id, infection) VALUES (5, 'Другие бактериальные кишечные инфекции');
INSERT INTO infection (id, infection) VALUES (6, 'Другие бактериальные пищевые отравления');
INSERT INTO infection (id, infection) VALUES (7, 'Амебиаз');
INSERT INTO infection (id, infection) VALUES (8, 'Другие протозойные кишечные болезни');
INSERT INTO infection (id, infection) VALUES (9, 'Вирусные и другие уточненные кишечные инфекции');
INSERT INTO infection (id, infection) VALUES (10, 'Диарея и гастроэнтерит предположительно инфекционного происхождения');
INSERT INTO infection (id, infection) VALUES (11, 'Туберкулез органов дыхания, подтвержденный бактериологически и гистологически');
INSERT INTO infection (id, infection) VALUES (12, 'Туберкулез органов дыхания, не подтвержденный бактериологически или гистологически');
INSERT INTO infection (id, infection) VALUES (13, 'Туберкулез нервной системы');
INSERT INTO infection (id, infection) VALUES (14, 'Туберкулез других органов');
INSERT INTO infection (id, infection) VALUES (15, 'Милиарный туберкулез');
INSERT INTO infection (id, infection) VALUES (16, 'Чума');
INSERT INTO infection (id, infection) VALUES (17, 'Туляремия');
INSERT INTO infection (id, infection) VALUES (18, 'Сибирская язва');
INSERT INTO infection (id, infection) VALUES (19, 'Бруцеллез');
INSERT INTO infection (id, infection) VALUES (20, 'Сап и мелиоидоз');
INSERT INTO infection (id, infection) VALUES (21, 'Лихорадка от укуса крыс');
INSERT INTO infection (id, infection) VALUES (22, 'Эризипелоид');
INSERT INTO infection (id, infection) VALUES (23, 'Лептоспироз');
INSERT INTO infection (id, infection) VALUES (24, 'Другие бактериальные зоонозы, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (25, 'Лепра [болезнь Гансена]');
INSERT INTO infection (id, infection) VALUES (26, 'Инфекции, вызванные другими микобактериями');
INSERT INTO infection (id, infection) VALUES (27, 'Листериоз');
INSERT INTO infection (id, infection) VALUES (28, 'Столбняк новорожденного');
INSERT INTO infection (id, infection) VALUES (29, 'Акушерский столбняк');
INSERT INTO infection (id, infection) VALUES (30, 'Другие формы столбняка');
INSERT INTO infection (id, infection) VALUES (31, 'Дифтерия');
INSERT INTO infection (id, infection) VALUES (32, 'Коклюш');
INSERT INTO infection (id, infection) VALUES (33, 'Скарлатина');
INSERT INTO infection (id, infection) VALUES (34, 'Менингококковая инфекция');
INSERT INTO infection (id, infection) VALUES (35, 'Стрептококковая септицемия');
INSERT INTO infection (id, infection) VALUES (36, 'Другая септицемия');
INSERT INTO infection (id, infection) VALUES (37, 'Актиномикоз');
INSERT INTO infection (id, infection) VALUES (38, 'Нокардиоз');
INSERT INTO infection (id, infection) VALUES (39, 'Бартонеллез');
INSERT INTO infection (id, infection) VALUES (40, 'Рожа');
INSERT INTO infection (id, infection) VALUES (41, 'Другие бактериальные болезни, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (42, 'Бактериальная инфекция неуточненной локализации');
INSERT INTO infection (id, infection) VALUES (43, 'Врожденный сифилис');
INSERT INTO infection (id, infection) VALUES (44, 'Ранний сифилис');
INSERT INTO infection (id, infection) VALUES (45, 'Поздний сифилис');
INSERT INTO infection (id, infection) VALUES (46, 'Другие и неуточненные формы сифилиса');
INSERT INTO infection (id, infection) VALUES (47, 'Гонококковая инфекция');
INSERT INTO infection (id, infection) VALUES (48, 'Хламидийная лимфогранулема (венерическая)');
INSERT INTO infection (id, infection) VALUES (49, 'Другие хламидийные болезни, передающиеся половым путем');
INSERT INTO infection (id, infection) VALUES (50, 'Шанкроид');
INSERT INTO infection (id, infection) VALUES (51, 'Паховая гранулема');
INSERT INTO infection (id, infection) VALUES (52, 'Трихомониаз');
INSERT INTO infection (id, infection) VALUES (53, 'Аногенитальная герпетическая вирусная инфекция [herpes simplex]');
INSERT INTO infection (id, infection) VALUES (54, 'Другие болезни, передающиеся преимущественно половым путем, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (55, 'Болезни, передающиеся половым путем, неуточненные');
INSERT INTO infection (id, infection) VALUES (56, 'Невенерический сифилис');
INSERT INTO infection (id, infection) VALUES (57, 'Фрамбезия');
INSERT INTO infection (id, infection) VALUES (58, 'Пинта [карате]');
INSERT INTO infection (id, infection) VALUES (59, 'Возвратные лихорадки');
INSERT INTO infection (id, infection) VALUES (60, 'Другие инфекции, вызванные спирохетами');
INSERT INTO infection (id, infection) VALUES (61, 'Инфекция, вызываемая Chlamydia psittaci');
INSERT INTO infection (id, infection) VALUES (62, 'Трахома');
INSERT INTO infection (id, infection) VALUES (63, 'Другие болезни, вызываемые хламидиями');
INSERT INTO infection (id, infection) VALUES (64, 'Сыпной тиф');
INSERT INTO infection (id, infection) VALUES (65, 'Пятнистая лихорадка [клещевые риккетсиозы]');
INSERT INTO infection (id, infection) VALUES (66, 'Лихорадка Ку');
INSERT INTO infection (id, infection) VALUES (67, 'Другие риккетсиозы');
INSERT INTO infection (id, infection) VALUES (68, 'Острый полиомиелит');
INSERT INTO infection (id, infection) VALUES (69, 'Медленные вирусные инфекции центральной нервной системы');
INSERT INTO infection (id, infection) VALUES (70, 'Бешенство');
INSERT INTO infection (id, infection) VALUES (71, 'Комариный вирусный энцефалит');
INSERT INTO infection (id, infection) VALUES (72, 'Клещевой вирусный энцефалит');
INSERT INTO infection (id, infection) VALUES (73, 'Другие вирусные энцефалиты, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (74, 'Вирусный энцефалит неуточненный');
INSERT INTO infection (id, infection) VALUES (75, 'Вирусный менингит');
INSERT INTO infection (id, infection) VALUES (76, 'Другие вирусные инфекции центральной нервной системы, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (77, 'Вирусная инфекция  центральной нервной системы неуточненная');
INSERT INTO infection (id, infection) VALUES (78, 'Лихорадка денге [классическая лихорадка денге]');
INSERT INTO infection (id, infection) VALUES (79, 'Геморрагическая лихорадка, вызванная вирусом денге');
INSERT INTO infection (id, infection) VALUES (80, 'Другие комариные вирусные лихорадки');
INSERT INTO infection (id, infection) VALUES (81, 'Другие вирусные лихорадки, передаваемые членистоногими, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (82, 'Вирусная лихорадка, передаваемая членистоногими, неуточненная');
INSERT INTO infection (id, infection) VALUES (83, 'Желтая лихорадка');
INSERT INTO infection (id, infection) VALUES (84, 'Ареновирусная геморрагическая лихорадка');
INSERT INTO infection (id, infection) VALUES (85, 'Другие вирусные геморрагические лихорадки, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (86, 'Вирусная геморрагическая лихорадка неуточненная');
INSERT INTO infection (id, infection) VALUES (87, 'Инфекции, вызванные вирусом герпеса [herpes simplex]');
INSERT INTO infection (id, infection) VALUES (88, 'Ветряная оспа [varicella]');
INSERT INTO infection (id, infection) VALUES (89, 'Опоясывающий лишай [herpes zoster]');
INSERT INTO infection (id, infection) VALUES (90, 'Оспа');
INSERT INTO infection (id, infection) VALUES (91, 'Инфекции, вызванные вирусом обезьяньей оспы');
INSERT INTO infection (id, infection) VALUES (92, 'Корь');
INSERT INTO infection (id, infection) VALUES (93, 'Краснуха [немецкая корь]');
INSERT INTO infection (id, infection) VALUES (94, 'Вирусные бородавки');
INSERT INTO infection (id, infection) VALUES (95, 'Другие вирусные инфекции, характеризующиеся поражениями кожи и слизистых оболочек, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (96, 'Вирусная инфекция, характеризующаяся поражением кожи и слизистых оболочек, неуточненная');
INSERT INTO infection (id, infection) VALUES (97, 'Острый гепатит A');
INSERT INTO infection (id, infection) VALUES (98, 'Острый гепатит B');
INSERT INTO infection (id, infection) VALUES (99, 'Другие острые вирусные гепатиты');
INSERT INTO infection (id, infection) VALUES (100, 'Хронический вирусный гепатит');
INSERT INTO infection (id, infection) VALUES (101, 'Вирусный гепатит неуточненный');
INSERT INTO infection (id, infection) VALUES (102, 'Болезнь, вызванная вирусом иммунодефицита человека [ВИЧ], проявляющаяся в виде инфекционных и паразитарных болезней');
INSERT INTO infection (id, infection) VALUES (103, 'Болезнь, вызванная вирусом иммунодефицита человека [ВИЧ], проявляющаяся в виде злокачественных новообразований');
INSERT INTO infection (id, infection) VALUES (104, 'Болезнь, вызванная вирусом иммунодефицита человека [ВИЧ], проявляющаяся в виде других уточненных болезней');
INSERT INTO infection (id, infection) VALUES (105, 'Болезнь, вызванная вирусом иммунодефицита человека  [ВИЧ], проявляющаяся в виде других состояний');
INSERT INTO infection (id, infection) VALUES (106, 'Болезнь, вызванная вирусом иммунодефицита человека [ВИЧ], неуточненная');
INSERT INTO infection (id, infection) VALUES (107, 'Цитомегаловирусная болезнь');
INSERT INTO infection (id, infection) VALUES (108, 'Эпидемический паротит');
INSERT INTO infection (id, infection) VALUES (109, 'Инфекционный мононуклеоз');
INSERT INTO infection (id, infection) VALUES (110, 'Вирусный конъюнктивит');
INSERT INTO infection (id, infection) VALUES (111, 'Другие вирусные болезни, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (112, 'Вирусная инфекция неуточненной локализации');
INSERT INTO infection (id, infection) VALUES (113, 'Дерматофития');
INSERT INTO infection (id, infection) VALUES (114, 'Другие поверхностные микозы');
INSERT INTO infection (id, infection) VALUES (115, 'Кандидоз');
INSERT INTO infection (id, infection) VALUES (116, 'Кокцидиоидомикоз');
INSERT INTO infection (id, infection) VALUES (117, 'Гистоплазмоз');
INSERT INTO infection (id, infection) VALUES (118, 'Бластомикоз');
INSERT INTO infection (id, infection) VALUES (119, 'Паракокцидиоидомикоз');
INSERT INTO infection (id, infection) VALUES (120, 'Споротрихоз');
INSERT INTO infection (id, infection) VALUES (121, 'Хромомикоз и феомикотический абсцесс');
INSERT INTO infection (id, infection) VALUES (122, 'Аспергиллез');
INSERT INTO infection (id, infection) VALUES (123, 'Криптококкоз');
INSERT INTO infection (id, infection) VALUES (124, 'Зигомикоз');
INSERT INTO infection (id, infection) VALUES (125, 'Мицетома');
INSERT INTO infection (id, infection) VALUES (126, 'Другие микозы, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (127, 'Микоз неуточненный');
INSERT INTO infection (id, infection) VALUES (128, 'Малярия, вызванная Plasmodium falciparum');
INSERT INTO infection (id, infection) VALUES (129, 'Малярия, вызванная Plasmodium vivax');
INSERT INTO infection (id, infection) VALUES (130, 'Малярия, вызванная Plasmodium malariae');
INSERT INTO infection (id, infection) VALUES (131, 'Другие виды паразитологически подтвержденной малярии');
INSERT INTO infection (id, infection) VALUES (132, 'Малярия неуточненная');
INSERT INTO infection (id, infection) VALUES (133, 'Лейшманиоз');
INSERT INTO infection (id, infection) VALUES (134, 'Африканский трипаносомоз');
INSERT INTO infection (id, infection) VALUES (135, 'Болезнь Шагаса');
INSERT INTO infection (id, infection) VALUES (136, 'Токсоплазмоз');
INSERT INTO infection (id, infection) VALUES (137, 'Пневмоцистоз');
INSERT INTO infection (id, infection) VALUES (138, 'Другие протозойные болезни, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (139, 'Протозойная болезнь неуточненная');
INSERT INTO infection (id, infection) VALUES (140, 'Шистосомоз [бильгарциоз]');
INSERT INTO infection (id, infection) VALUES (141, 'Другие трематодозы');
INSERT INTO infection (id, infection) VALUES (142, 'Эхинококкоз');
INSERT INTO infection (id, infection) VALUES (143, 'Тениоз');
INSERT INTO infection (id, infection) VALUES (144, 'Цистицеркоз');
INSERT INTO infection (id, infection) VALUES (145, 'Дифиллоботриоз и спарганоз');
INSERT INTO infection (id, infection) VALUES (146, 'Другие инвазии, вызванные цестодами');
INSERT INTO infection (id, infection) VALUES (147, 'Дракункулез');
INSERT INTO infection (id, infection) VALUES (148, 'Онхоцеркоз');
INSERT INTO infection (id, infection) VALUES (149, 'Филяриатоз');
INSERT INTO infection (id, infection) VALUES (150, 'Трихинеллез');
INSERT INTO infection (id, infection) VALUES (151, 'Анкилостомидоз');
INSERT INTO infection (id, infection) VALUES (152, 'Аскаридоз');
INSERT INTO infection (id, infection) VALUES (153, 'Стронгилоидоз');
INSERT INTO infection (id, infection) VALUES (154, 'Трихуроз');
INSERT INTO infection (id, infection) VALUES (155, 'Энтеробиоз');
INSERT INTO infection (id, infection) VALUES (156, 'Другие кишечные гельминтозы, не классифицированные в других рубриках');
INSERT INTO infection (id, infection) VALUES (157, 'Кишечный паразитизм неуточненный');
INSERT INTO infection (id, infection) VALUES (158, 'Другие гельминтозы');
INSERT INTO infection (id, infection) VALUES (159, 'Педикулез и фтириоз');
INSERT INTO infection (id, infection) VALUES (160, 'Чесотка');
INSERT INTO infection (id, infection) VALUES (161, 'Миаз');
INSERT INTO infection (id, infection) VALUES (162, 'Другие инфестации');
INSERT INTO infection (id, infection) VALUES (163, 'Паразитарная болезнь неуточненная');
INSERT INTO infection (id, infection) VALUES (164, 'Последствия туберкулеза');
INSERT INTO infection (id, infection) VALUES (165, 'Последствия полиомиелита');
INSERT INTO infection (id, infection) VALUES (166, 'Последствия лепры');
INSERT INTO infection (id, infection) VALUES (167, 'Последствия других и неуточненных инфекционных и паразитарных болезней');
INSERT INTO infection (id, infection) VALUES (168, 'Стрептококки и стафилококки как причина болезней, классифицированных в других рубриках');
INSERT INTO infection (id, infection) VALUES (169, 'Другие бактериальные агенты как причина болезней, классифицированных в других рубриках');
INSERT INTO infection (id, infection) VALUES (170, 'Вирусные агенты как причина болезней, классифицированных в других рубриках');