# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(blank=True, max_length=100, verbose_name='\u0422\u0438\u043f \u0442\u0435\u043b\u043e\u0441\u043b\u043e\u0436\u0435\u043d\u0438\u044f')),
            ],
            options={
                'db_table': 'body_types',
            },
        ),
        migrations.CreateModel(
            name='BonesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bones_type', models.CharField(max_length=150, verbose_name='\u0422\u0438\u043f \u043a\u043e\u0441\u0442\u0435\u0439')),
            ],
            options={
                'db_table': 'bones_types',
            },
        ),
        migrations.CreateModel(
            name='CardiovascularSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_viewed', models.CharField(max_length=150, verbose_name='\u041f\u0440\u0438 \u043e\u0441\u043c\u043e\u0442\u0440\u0435')),
                ('epigastric_pulsation', models.CharField(max_length=150, verbose_name='\u042d\u043f\u0438\u0433\u0430\u0441\u0442\u0440\u0430\u043b\u044c\u043d\u0430\u044f \u043f\u0443\u043b\u044c\u043f\u0430\u0446\u0438\u044f')),
                ('visible_heart_pulsation', models.CharField(max_length=150, verbose_name='\u0412\u0438\u0434\u0438\u043c\u044b\u0435 \u043d\u0430 \u0433\u043b\u0430\u0437 \u0441\u0435\u0440\u0434\u0435\u0447\u043d\u044b\u0435 \u043f\u0443\u043b\u044c\u0441\u0430\u0446\u0438\u0438')),
                ('cyanosis', models.CharField(max_length=150, verbose_name='\u0426\u0438\u0430\u043d\u043e\u0437')),
                ('apical_impulse', models.CharField(max_length=150, verbose_name='\u0412\u0435\u0440\u0445\u0443\u0448\u0435\u0447\u043d\u044b\u0439 \u0442\u043e\u043b\u0447\u043e\u043a ')),
                ('between_ribs', models.IntegerField(verbose_name='\u041c\u0435\u0436\u0440\u0435\u0431\u0440\u0438\u0435')),
                ('left_bound_heart', models.CharField(max_length=150, verbose_name='\u041b\u0435\u0432\u0430\u044f \u0433\u0440\u0430\u043d\u0438\u0446\u0430 \u0441\u0435\u0440\u0434\u0446\u0430 ')),
                ('right_bound_heart', models.CharField(max_length=150, verbose_name='\u041f\u0440\u0430\u0432\u0430\u044f \u0433\u0440\u0430\u043d\u0438\u0446\u0430 \u0441\u0435\u0440\u0434\u0446\u0430 ')),
                ('top_bound_heart', models.CharField(max_length=150, verbose_name='\u0412\u0435\u0440\u0445\u043d\u044f\u044f \u0433\u0440\u0430\u043d\u0438\u0446\u0430 \u0441\u0435\u0440\u0434\u0446\u0430 ')),
                ('vacular_bundle', models.CharField(max_length=150, verbose_name='\u0421\u043e\u0441\u0443\u0434\u0438\u0441\u0442\u044b\u0439 \u043f\u0443\u0447\u043e\u043a')),
                ('ausculation_heart_top', models.CharField(max_length=150, verbose_name='\u0410\u0443\u0441\u043a\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u044f \u0441\u0435\u0440\u0434\u0446\u0430: \u041d\u0430 \u0432\u0435\u0440\u0445\u0443\u0448\u043a\u0435')),
                ('systolic_murmur', models.CharField(max_length=150, verbose_name='\u0421\u0438\u0441\u0442\u043e\u043b\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0448\u0443\u043c')),
                ('diastolic_murmur', models.CharField(max_length=150, verbose_name='\u0414\u0438\u0430\u0441\u0442\u043e\u043b\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0448\u0443\u043c')),
                ('aorta', models.CharField(max_length=150, verbose_name='\u041d\u0430 \u0430\u043e\u0440\u0442\u0435')),
                ('systolic_diastolic_noise', models.CharField(max_length=150, verbose_name='\u0421\u0438\u0441\u0442\u043e\u043b\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0438 \u0434\u0438\u0430\u0441\u0442\u043e\u043b\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0448\u0443\u043c\u044b')),
                ('in_pulmonary_artery', models.CharField(max_length=150, verbose_name='\u041d\u0430 \u043b\u0435\u0433\u043e\u0447\u043d\u043e\u0439 \u0430\u0440\u0442\u0435\u0440\u0438\u0438')),
                ('systolic_diastolic_noise_2', models.CharField(max_length=150, verbose_name='\u0421\u0438\u0441\u0442\u043e\u043b\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0438 \u0434\u0438\u0430\u0441\u0442\u043e\u043b\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0448\u0443\u043c\u044b')),
                ('flap_3_valve', models.CharField(max_length=150, verbose_name='\u041d\u0430 3-\u0445 \u0441\u0442\u0432\u043e\u0440\u0447\u0430\u0442\u043e\u043c \u043a\u043b\u0430\u043f\u0430\u043d\u0435')),
                ('left_ebge_sternum', models.CharField(max_length=150, verbose_name='\u041f\u043e \u043b\u0435\u0432\u043e\u043c\u0443 \u043a\u0440\u0430\u044e \u0433\u0440\u0443\u0434\u0438\u043d\u044b')),
                ('arteries', models.CharField(max_length=150, verbose_name='\u0410\u0440\u0442\u0435\u0440\u0438\u0438')),
                ('viens', models.CharField(max_length=150, verbose_name='\u0412\u0435\u043d\u044b')),
                ('pulse_rhythm', models.CharField(max_length=150, verbose_name='\u041f\u0443\u043b\u044c\u0441-\u0420\u0438\u0442\u043c ')),
                ('frequency', models.CharField(max_length=150, verbose_name='\u0427\u0430\u0441\u0442\u043e\u0442\u0430')),
                ('myosphhygmia', models.CharField(max_length=150, verbose_name='\u0414\u0435\u0444\u0438\u0446\u0438\u0442 \u043f\u0443\u043b\u044c\u0441\u0430')),
                ('blood_pressure', models.CharField(max_length=150, verbose_name='\u0410\u0440\u0442\u0435\u0440\u0438\u0430\u043b\u044c\u043d\u043e\u0435 \u0434\u0430\u0432\u043b\u0435\u043d\u0438\u0435')),
                ('noise_around_umbilical_area', models.CharField(max_length=150, verbose_name='\u0428\u0443\u043c \u043e\u043a\u043e\u043b\u043e \u043f\u0443\u043f\u043e\u0447\u043d\u043e\u0439 \u043e\u0431\u043b\u0430\u0441\u0442\u0438')),
            ],
            options={
                'db_table': 'cardiovascular_system',
                'verbose_name': '\u0421\u0435\u0440\u0434\u0435\u0447\u043d\u043e \u0441\u043e\u0441\u0443\u0434\u0438\u0441\u0442\u0430\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u0430',
                'verbose_name_plural': '\u0421\u0435\u0440\u0434\u0435\u0447\u043d\u043e \u0441\u043e\u0441\u0443\u0434\u0438\u0441\u0442\u0430\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u0430',
            },
        ),
        migrations.CreateModel(
            name='DigestiveSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oral_musosa', models.CharField(max_length=150, verbose_name='\u0421\u043b\u0438\u0437\u0438\u0441\u0442\u0430\u044f \u043f\u043e\u043b\u043e\u0441\u0430 \u0440\u0442\u0430')),
                ('teeth', models.CharField(max_length=150, verbose_name='\u0417\u0443\u0431\u044b')),
                ('tongue', models.CharField(max_length=150, verbose_name='\u042f\u0437\u044b\u043a')),
                ('pharynx', models.CharField(max_length=150, verbose_name='\u0417\u0435\u0432')),
                ('tonsils', models.CharField(max_length=150, verbose_name='\u041c\u0438\u043d\u0434\u0430\u043b\u0438\u043d\u044b')),
                ('stomach', models.CharField(max_length=150, verbose_name='\u0416\u0438\u0432\u043e\u0442')),
                ('liver', models.CharField(max_length=150, verbose_name='\u041f\u0435\u0447\u0435\u043d\u044c')),
                ('lower_midclavicularline', models.CharField(max_length=150, verbose_name='\u041d\u0438\u0436\u043d\u044f\u044f \u043f\u043e \u0441\u0440\u0435\u0434\u043d\u0435\u043a\u043b\u044e\u0447\u0438\u0447\u043d\u043e\u0439 \u043b\u0438\u043d\u0438\u0438 ')),
                ('left_costal_arch', models.CharField(max_length=150, verbose_name='\u041b\u0435\u0432\u043e\u0439 \u0440\u0435\u0431\u0435\u0440\u043d\u043e\u0439 \u0434\u0443\u0433\u0435')),
                ('palpation_edge', models.CharField(max_length=150, verbose_name='\u041f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438 \u043a\u0440\u0430\u044f')),
                ('surface', models.CharField(max_length=150, verbose_name='\u041f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u044c')),
                ('soreness', models.CharField(max_length=150, verbose_name='\u0411\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043d\u043e\u0441\u0442\u044c')),
                ('consistency', models.CharField(max_length=150, verbose_name='\u041a\u043e\u043d\u0441\u0438\u0441\u0442\u0435\u043d\u0446\u0438\u044f')),
                ('gallbladder', models.CharField(max_length=150, verbose_name='\u0416\u0435\u043b\u0447\u043d\u044b\u0439 \u043f\u0443\u0437\u044b\u0440\u044c')),
                ('pancreas', models.CharField(max_length=150, verbose_name='\u041f\u043e\u0434\u0436\u0435\u043b\u0443\u0434\u043e\u0447\u043d\u0430\u044f \u0436\u0435\u043b\u0435\u0437\u0430')),
                ('spleen', models.CharField(max_length=150, verbose_name='\u0421\u0435\u043b\u0435\u0437\u0435\u043d\u043a\u0430')),
                ('boundaries', models.CharField(max_length=150, verbose_name='\u0413\u0440\u0430\u043d\u0438\u0446\u044b ')),
                ('bottom_line', models.CharField(max_length=150, verbose_name='\u041d\u0438\u0436\u043d\u044f\u044f \u0433\u0440\u0430\u043d\u0438\u0446\u0430')),
                ('on_palpation_edbe', models.CharField(max_length=150, verbose_name='\u041f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043a\u0440\u0430\u044f')),
                ('bl_surface', models.CharField(max_length=150, verbose_name='\u041f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u044c')),
                ('bl_tenderness', models.CharField(max_length=150, verbose_name='\u041f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043e\u0441\u0442\u044c')),
                ('bl_consistency', models.CharField(max_length=150, verbose_name='\u041f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u043a\u043e\u043d\u0441\u0438\u0441\u0442\u0435\u043d\u0446\u0438\u044f')),
                ('stools', models.CharField(max_length=150, verbose_name='\u0421\u0442\u0443\u043b (\u0441\u043e \u0441\u043b\u043e\u0432 \u043f\u0430\u0446\u0438\u0435\u043d\u0442\u0430)')),
            ],
            options={
                'db_table': 'digestive_system',
                'verbose_name': '\u0421\u0438\u0441\u0442\u0435\u043c\u0430 \u043f\u0438\u0449\u0435\u0432\u0430\u0440\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0421\u0438\u0441\u0442\u0435\u043c\u0430 \u043f\u0438\u0449\u0435\u0432\u0430\u0440\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField(verbose_name='\u0422\u0440\u0430\u0432\u043c\u044b')),
            ],
            options={
                'db_table': 'disease',
                'verbose_name': '\u0422\u0440\u0430\u0432\u043c\u0430',
                'verbose_name_plural': '\u0422\u0440\u0430\u0432\u043c\u044b',
            },
        ),
        migrations.CreateModel(
            name='EndocrineSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thyroid_gland', models.CharField(max_length=150, verbose_name='\u0429\u0438\u0442\u043e\u0432\u0438\u0434\u043d\u0430\u044f \u0436\u0435\u043b\u0435\u0437\u0430')),
                ('eye_symptoms', models.CharField(max_length=150, verbose_name='\u0413\u043b\u0430\u0437\u043d\u044b\u0435 \u0441\u0438\u043c\u043f\u0442\u043e\u043c\u044b')),
            ],
            options={
                'db_table': 'endocrine_system',
                'verbose_name': '\u042d\u043d\u0434\u043e\u043a\u0440\u0438\u043d\u043d\u0430\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u0430',
                'verbose_name_plural': '\u042d\u043d\u0434\u043e\u043a\u0440\u0438\u043d\u043d\u0430\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u0430',
            },
        ),
        migrations.CreateModel(
            name='GenitoUrinarySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urination', models.CharField(max_length=150, verbose_name='\u041c\u043e\u0447\u0435\u0438\u0441\u043f\u0443\u0441\u043a\u0430\u043d\u0438\u0435')),
                ('symptoms_tapping_edge_12', models.CharField(max_length=150, verbose_name='\u0421\u0438\u043c\u043f\u0442\u043e\u043c\u044b \u043f\u043e\u043a\u0430\u043b\u044b\u0432\u0430\u043d\u0438\u044f \u043f\u043e  \u0440\u0435\u0431\u0440\u0443')),
                ('palpation_kidneys', models.CharField(max_length=150, verbose_name='\u041f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u044f \u043f\u043e\u0447\u0435\u043a')),
                ('urinary_bladder', models.CharField(max_length=150, verbose_name='\u041c\u043e\u0447\u0435\u0432\u043e\u0439 \u043f\u0443\u0437\u044b\u0440\u044c')),
                ('genitals', models.TextField(verbose_name='\u041f\u043e\u043b\u043e\u0432\u044b\u0435 \u043e\u0440\u0433\u0430\u043d\u044b')),
            ],
            options={
                'db_table': 'genito_urinary_system',
                'verbose_name': '\u041c\u043e\u0447\u0435\u043f\u043e\u043b\u043e\u0432\u0430\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u0430',
                'verbose_name_plural': '\u041c\u043e\u0447\u0435\u043f\u043e\u043b\u043e\u0432\u0430\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u0430',
            },
        ),
        migrations.CreateModel(
            name='HistoryPatientLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_conditions', models.CharField(choices=[('\u0443\u0434\u043e\u0432\u043b\u0435\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435', '\u0443\u0434\u043e\u0432\u043b\u0435\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435'), ('\u043d\u0435\u0443\u0434\u043e\u0432\u043b\u0435\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435', '\u043d\u0435\u0443\u0434\u043e\u0432\u043b\u0435\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435'), ('\u0445\u043e\u0440\u043e\u0448\u0438\u0435', '\u0445\u043e\u0440\u043e\u0448\u0438\u0435')], max_length=150, verbose_name='\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u043e \u0431\u044b\u0442\u043e\u0432\u044b\u0435 \u0443\u0441\u043b\u043e\u0432\u0438\u044f')),
                ('harmful_profession', models.CharField(max_length=300, verbose_name='\u041f\u0440\u043e\u0444\u0432\u0440\u0435\u0434\u043d\u043e\u0441\u0442\u0438')),
                ('retired', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041d\u0430 \u043f\u0435\u043d\u0441\u0438\u0438 (\u0432\u043e\u0437\u0440\u0430\u0441\u0442)')),
                ('disability_group', models.PositiveIntegerField(blank=True, choices=[(1, '\u041f\u0435\u0440\u0432\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430'), (2, '\u0412\u0442\u043e\u0440\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430'), (3, '\u0422\u0440\u0435\u0442\u044c\u044f \u0433\u0440\u0443\u043f\u043f\u0430')], verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0438\u043d\u0432\u0430\u043b\u0438\u0434\u043d\u043e\u0441\u0442\u0438')),
                ('disability_years', models.DateField(blank=True, null=True, verbose_name='\u0418\u043d\u0432\u0430\u043b\u0438\u0434\u043d\u043e\u0441\u0442\u044c \u0441 \u0433\u043e\u0434\u0430')),
                ('smoking_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041a\u0443\u0440\u0435\u043d\u0438\u0435 (\u0441 \u043b\u0435\u0442)')),
                ('smoking_packs_day', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041a\u0443\u0440\u0435\u043d\u0438\u0435 \u043f\u0430\u0447\u0435\u043a \u0432 \u0434\u0435\u043d\u044c')),
                ('alcohol_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0423\u043f\u043e\u0442\u0440\u0435\u0431\u043b\u0435\u043d\u0438\u0435 \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044f(\u0432\u043e\u0437\u0440\u0430\u0441\u0442)')),
                ('allergic_history', models.TextField(verbose_name='\u0410\u043b\u043b\u0435\u0440\u0433\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0430\u043d\u0435\u043c\u0435\u0437')),
                ('risk_factors', models.TextField(verbose_name='\u0424\u0430\u043a\u0442\u043e\u0440\u044b \u0440\u0438\u0441\u043a\u0430')),
                ('patient', models.IntegerField(verbose_name='\u041f\u0430\u0446\u0438\u0435\u043d\u0442')),
                ('disease', models.ManyToManyField(blank=True, related_name='diseases', to='medicalhistory.Disease', verbose_name='\u0422\u0440\u0430\u0432\u043c\u044b \u0438 \u0431\u043e\u043b\u0435\u0437\u043d\u0438')),
            ],
            options={
                'db_table': 'history_patient_life',
                'verbose_name': '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u0436\u0438\u0437\u043d\u0438 \u043f\u0430\u0446\u0438\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0440\u0438\u0438 \u0436\u0438\u0437\u043d\u0438 \u043f\u0430\u0446\u0438\u0435\u043d\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='Infection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infection', models.TextField(verbose_name='\u0418\u043d\u0444\u0435\u043a\u0446\u0438\u0438')),
            ],
            options={
                'db_table': 'infection',
                'verbose_name': '\u0418\u043d\u0444\u0435\u043a\u0446\u0438\u043e\u043d\u043d\u043e\u0435 \u0437\u0430\u0431\u043e\u043b\u0435\u0432\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0418\u043d\u0444\u0435\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0435 \u0437\u0430\u0431\u043e\u043b\u0435\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='JointsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joints_type', models.CharField(max_length=150, verbose_name='\u0422\u0438\u043f \u0441\u0443\u0441\u0442\u0430\u0432\u043e\u0432')),
            ],
            options={
                'db_table': 'joints_types',
            },
        ),
        migrations.CreateModel(
            name='LymphNodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lymph_node_type', models.CharField(max_length=150, verbose_name='\u041b\u0438\u043c\u0444\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0443\u0437\u043b\u044b')),
            ],
            options={
                'db_table': 'lymphnode_types',
            },
        ),
        migrations.CreateModel(
            name='MenstruationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menstruation_type', models.CharField(max_length=120, verbose_name='\u0422\u0438\u043f \u043c\u0435\u043d\u0441\u0442\u0440\u0443\u0430\u0446\u0438\u0438')),
            ],
            options={
                'db_table': 'menstruation_types',
            },
        ),
        migrations.CreateModel(
            name='MusclesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscles_type', models.CharField(max_length=150, verbose_name='\u0422\u0438\u043f \u043c\u044b\u0449\u0446\u044b')),
            ],
            options={
                'db_table': 'muscles_types',
            },
        ),
        migrations.CreateModel(
            name='NailsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nails_type', models.CharField(max_length=150, verbose_name='\u0422\u0438\u043f \u043d\u043e\u0433\u0442\u0435\u0439')),
            ],
            options={
                'db_table': 'nails_types',
            },
        ),
        migrations.CreateModel(
            name='NeuroPsychologicalSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consciousness', models.CharField(max_length=150, verbose_name='\u0421\u043e\u0437\u043d\u0430\u043d\u0438\u0435')),
                ('neurological_status', models.CharField(choices=[('\u0432\u043e\u0441\u043f\u0440\u0438\u043d\u0438\u043c\u0430\u0435\u0442 \u0445\u043e\u0440\u043e\u0448\u043e', '\u0432\u043e\u0441\u043f\u0440\u0438\u043d\u0438\u043c\u0430\u0435\u0442 \u0445\u043e\u0440\u043e\u0448\u043e'), ('\u0441\u043d\u0438\u0436\u0435\u043d\u043e', '\u0441\u043d\u0438\u0436\u0435\u043d\u043e'), ('\u0443\u0442\u0440\u0430\u0447\u0435\u043d\u043e', '\u0443\u0442\u0440\u0430\u0447\u0435\u043d\u043e')], max_length=150, verbose_name='\u041d\u0435\u0432\u0440\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0441\u0442\u0430\u0442\u0443\u0441')),
                ('eye_slits', models.CharField(max_length=150, verbose_name='\u0413\u043b\u0430\u0437\u043d\u044b\u0435 \u0449\u0435\u043b\u0438')),
                ('pupils', models.CharField(max_length=150, verbose_name='\u0417\u0440\u0430\u0447\u043a\u0438')),
                ('movement_eyeballs', models.CharField(max_length=150, verbose_name='\u0414\u0432\u0438\u0436\u0435\u043d\u0438\u044f \u0433\u043b\u0430\u0437\u043d\u044b\u0445 \u044f\u0431\u043b\u043e\u043a')),
                ('face', models.CharField(max_length=150, verbose_name='\u041b\u0438\u0446\u043e')),
                ('dizziness', models.CharField(max_length=150, verbose_name='\u0413\u043e\u043b\u043e\u0432\u043e\u043a\u0440\u0443\u0436\u0435\u043d\u0438\u0435')),
                ('swallowing', models.CharField(max_length=150, verbose_name='\u0413\u043b\u043e\u0442\u0430\u043d\u0438\u0435')),
                ('protrude_tongue', models.CharField(max_length=150, verbose_name='\u042f\u0437\u044b\u043a \u043f\u0440\u0438 \u0432\u044b\u0441\u043e\u0432\u044b\u0432\u0430\u043d\u0438\u0438')),
                ('superficial_deepreflexes', models.CharField(max_length=150, verbose_name='\u041f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u043d\u044b\u0435 \u0438 \u0433\u043b\u0443\u0431\u043e\u043a\u0438\u0435 \u0440\u0435\u0444\u043b\u0435\u043a\u0441\u044b')),
                ('muscle_tone', models.CharField(max_length=150, verbose_name='\u041c\u044b\u0448\u0435\u0447\u043d\u044b\u0439 \u0442\u043e\u043d\u0443\u0441')),
                ('muscle_strength', models.CharField(max_length=150, verbose_name='\u041c\u044b\u0448\u0435\u0447\u043d\u0430\u044f \u0441\u0438\u043b\u0430')),
                ('sensitivity', models.CharField(max_length=150, verbose_name='\u0427\u0443\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
                ('parkinsonism_syndrome', models.CharField(max_length=150, verbose_name='\u0421\u0438\u043d\u0434\u0440\u043e\u043c \u041f\u0430\u0440\u043a\u0438\u043d\u0441\u043e\u043d\u0438\u0437\u043c\u0430')),
                ('functions_pelvicorgan', models.CharField(choices=[('\u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u044b', '\u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u044b'), ('\u043d\u0430\u0440\u0443\u0448\u0435\u043d\u044b', '\u043d\u0430\u0440\u0443\u0448\u0435\u043d\u044b')], max_length=150, verbose_name='\u0424\u0443\u043d\u043a\u0446\u0438\u0438 \u0442\u0430\u0437\u043e\u0432\u044b\u0445 \u043e\u0433\u0440\u0430\u043d\u043e\u0432')),
                ('meningeal_symptoms', models.CharField(max_length=150, verbose_name='\u041c\u0435\u043d\u0438\u043d\u0433\u0435\u0430\u043b\u044c\u043d\u044b\u0435 \u0421\u0438\u043c\u043f\u0442\u043e\u043c\u044b')),
                ('symptom_Kerning', models.CharField(max_length=150, verbose_name='\u0421\u0438\u043c\u043f\u0442\u043e\u043c \u041a\u0435\u0440\u043d\u0438\u043d\u0433')),
                ('memory', models.CharField(max_length=150, verbose_name='\u041f\u0430\u043c\u044f\u0442\u044c')),
                ('intellect', models.CharField(max_length=150, verbose_name='\u0418\u043d\u0442\u0435\u043b\u0435\u043a\u0442')),
                ('valetudinarianism', models.CharField(max_length=150, verbose_name='\u041c\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
                ('suggestibility', models.CharField(max_length=150, verbose_name='\u0412\u043d\u0443\u0448\u0430\u0435\u043c\u043e\u0441\u0442\u044c')),
                ('pathological_reflexes', models.CharField(max_length=150, verbose_name='\u041f\u0430\u0442\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0440\u0435\u0444\u043b\u0435\u043a\u0441\u044b')),
                ('autographism', models.CharField(max_length=150, verbose_name='\u0414\u0435\u0440\u043c\u043e\u0433\u0440\u0430\u0444\u0438\u0437\u043c')),
                ('romberg', models.CharField(max_length=150, verbose_name='\u0412 \u043f\u043e\u0437\u0435 \u0420\u043e\u043c\u0431\u0435\u0440\u0433\u0430')),
                ('history', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalhistory.HistoryPatientLife')),
            ],
            options={
                'db_table': 'neuro_psychological_system',
                'verbose_name': '\u041d\u0435\u0440\u0432\u043d\u043e-\u043f\u0441\u0438\u0445\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u0430',
                'verbose_name_plural': '\u041d\u0435\u0440\u0432\u043d\u043e-\u043f\u0441\u0438\u0445\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u0430',
            },
        ),
        migrations.CreateModel(
            name='PatientConditionsNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_state', models.TextField(blank=True, verbose_name='\u041e\u0431\u0449\u0435\u0435 \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435')),
                ('weight', models.FloatField(blank=True, verbose_name='\u0412\u0435\u0441')),
                ('height', models.FloatField(blank=True, verbose_name='\u0420\u043e\u0441\u0442')),
                ('body', models.CharField(blank=True, choices=[('\u0430\u0441\u0442\u0435\u043d\u0438\u0447\u0435\u0441\u043a\u043e\u0435', '\u0430\u0441\u0442\u0435\u043d\u0438\u0447\u0435\u0441\u043a\u043e\u0435'), ('\u043d\u043e\u0440\u043c\u043e\u0441\u0442\u0435\u043d\u0438\u0447\u0435\u0441\u043a\u043e\u0435', '\u043d\u043e\u0440\u043c\u043e\u0441\u0442\u0435\u043d\u0438\u0447\u0435\u0441\u043a\u043e\u0435'), ('\u0433\u0438\u043f\u0435\u0440\u0441\u0442\u0435\u043d\u0438\u0447\u0435\u0441\u043a\u043e\u0435', '\u0433\u0438\u043f\u0435\u0440\u0441\u0442\u0435\u043d\u0438\u0447\u0435\u0441\u043a\u043e\u0435')], max_length=100, verbose_name='\u0422\u0435\u043b\u043e\u0441\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('position', models.CharField(blank=True, choices=[('\u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0435', '\u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0435'), ('\u0432\u044b\u043d\u0443\u0436\u0434\u0435\u043d\u043d\u043e\u0435', '\u0432\u044b\u043d\u0443\u0436\u0434\u0435\u043d\u043d\u043e\u0435')], max_length=150, verbose_name='\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('skin', models.CharField(blank=True, max_length=150, verbose_name='\u041a\u043e\u0436\u043d\u044b\u0435 \u043f\u043e\u043a\u0440\u043e\u0432\u044b')),
                ('subcutaneous_tissue', models.CharField(blank=True, max_length=150, verbose_name='\u041f\u043e\u0434\u043a\u043e\u0436\u043d\u0430\u044f \u043a\u043b\u0435\u0442\u0447\u0430\u0442\u043a\u0430')),
                ('nails', models.CharField(blank=True, max_length=150, verbose_name='\u041d\u043e\u0433\u0442\u0438')),
                ('muscles', models.CharField(blank=True, max_length=100, verbose_name='\u041c\u044b\u0449\u0446\u044b')),
                ('bones', models.CharField(blank=True, max_length=100, verbose_name='\u041a\u043e\u0441\u0442\u0438')),
                ('joints', models.CharField(blank=True, max_length=100, verbose_name='\u0421\u0443\u0441\u0442\u0430\u0432\u044b')),
                ('lymph_node', models.CharField(blank=True, max_length=150, verbose_name='\u041b\u0438\u043c\u0444\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0443\u0437\u043b\u044b')),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medicalhistory.HistoryPatientLife')),
            ],
            options={
                'db_table': 'patient_conditions_now',
                'verbose_name': '\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435 \u0431\u043e\u043b\u044c\u043d\u043e\u0433\u043e \u0432 \u0434\u0430\u043d\u043d\u044b\u0439 \u043c\u043e\u043c\u0435\u043d\u0442',
                'verbose_name_plural': '\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435 \u0431\u043e\u043b\u044c\u043d\u043e\u0433\u043e \u0432 \u0434\u0430\u043d\u043d\u044b\u0439 \u043c\u043e\u043c\u0435\u043d\u0442',
            },
        ),
        migrations.CreateModel(
            name='PlanSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_survey', models.TextField(verbose_name='\u041f\u043b\u0430\u043d \u043e\u0431\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('history', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalhistory.HistoryPatientLife')),
            ],
            options={
                'db_table': 'plan_survey',
                'verbose_name': '\u041f\u043b\u0430\u043d \u043e\u0431\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u041f\u043b\u0430\u043d \u043e\u0431\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(max_length=100, verbose_name='\u0422\u0438\u043f \u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u044f')),
            ],
            options={
                'db_table': 'position_types',
            },
        ),
        migrations.CreateModel(
            name='PregnancyProceedsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_proceeds_type', models.CharField(max_length=150, verbose_name='\u0422\u0438\u043f \u043f\u0440\u043e\u0442\u0435\u043a\u0430\u043d\u0438\u044f \u0431\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0441\u0442\u0438')),
            ],
            options={
                'db_table': 'pregnancy_proceeds_types',
            },
        ),
        migrations.CreateModel(
            name='RespiratorySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasal_breathing_type', models.CharField(blank=True, max_length=120, verbose_name='\u041d\u043e\u0441\u043e\u0432\u043e\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u0435')),
                ('rib_cage', models.CharField(max_length=150, verbose_name='\u0413\u0440\u0443\u0434\u043d\u0430\u044f \u043a\u043b\u0435\u0442\u043a\u0430')),
                ('participaton_chest_breathing', models.CharField(blank=True, choices=[('\u0441\u0438\u043c\u043c\u0435\u0442\u0440\u0438\u0447\u043d\u043e', '\u0441\u0438\u043c\u043c\u0435\u0442\u0440\u0438\u0447\u043d\u043e'), ('\u043e\u0442\u0441\u0442\u0430\u0435\u0442 \u0441\u043f\u0440\u0430\u0432\u0430', '\u043e\u0442\u0441\u0442\u0430\u0435\u0442 \u0441\u043f\u0440\u0430\u0432\u0430'), ('\u043e\u0442\u0441\u0442\u0430\u0435\u0442 \u0441\u043b\u0435\u0432\u0430', '\u043e\u0442\u0441\u0442\u0430\u0435\u0442 \u0441\u043b\u0435\u0432\u0430')], max_length=40, verbose_name='\u0423\u0447\u0430\u0441\u0442\u0438\u0435 \u0433\u0440\u0443\u0434\u043d\u043e\u0439 \u043a\u043b\u0435\u0442\u043a\u0438 \u0432 \u0430\u043a\u0442\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u044f')),
                ('participation_breathing_muscle', models.CharField(max_length=150, verbose_name='\u0423\u0447\u0430\u0441\u0442\u0438\u0435 \u0432 \u0430\u043a\u0442\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u044f \u043c\u044b\u0448\u0446')),
                ('voice_tremor', models.CharField(choices=[('\u043e\u0434\u0438\u043d\u0430\u043a\u043e\u0432\u043e\u0435 \u0441 \u043e\u0431\u0435\u0438\u0445 \u0441\u0442\u043e\u0440\u043e\u043d', '\u043e\u0434\u0438\u043d\u0430\u043a\u043e\u0432\u043e\u0435 \u0441 \u043e\u0431\u0435\u0438\u0445 \u0441\u0442\u043e\u0440\u043e\u043d'), ('\u0443\u0441\u0438\u043b\u0435\u043d\u043e', '\u0443\u0441\u0438\u043b\u0435\u043d\u043e'), ('\u043e\u0441\u043b\u0430\u0431\u043b\u0435\u043d\u043e', '\u043e\u0441\u043b\u0430\u0431\u043b\u0435\u043d\u043e')], max_length=150, verbose_name='\u0413\u043e\u043b\u043e\u0441\u043e\u0432\u043e\u0435 \u0434\u0440\u043e\u0436\u0430\u043d\u0438\u0435')),
                ('percussion_lung', models.CharField(max_length=150, verbose_name='\u041f\u0435\u0440\u043a\u0443\u0441\u0441\u0438\u044f \u043b\u0435\u0433\u043a\u0438\u0445')),
                ('omision_lower_bound', models.CharField(max_length=150, verbose_name='\u041e\u043f\u0443\u0449\u0435\u043d\u0438\u0435 \u043d\u0438\u0436\u043d\u0438\u0445 \u0433\u0440\u0430\u043d\u0438\u0446')),
                ('mobility_bottom_edbe_lungs', models.CharField(max_length=150, verbose_name='\u041f\u043e\u0434\u0432\u0438\u0436\u043d\u043e\u0441\u0442\u044c \u043d\u0438\u0436\u043d\u0435\u0433\u043e \u043a\u0440\u0430\u044f \u043b\u0435\u0433\u043a\u0438\u0445')),
                ('auscultation_lungs', models.CharField(max_length=150, verbose_name='\u0410\u0443\u0441\u043a\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u044f \u043b\u0435\u0433\u043a\u0438\u0445')),
                ('wheezing', models.CharField(max_length=150, verbose_name='\u0413\u0440\u0443\u0434\u043d\u0430\u044f \u043a\u043b\u0435\u0442\u043a\u0430')),
                ('number_breaths_perminute', models.CharField(max_length=150, verbose_name='\u0425\u0440\u0438\u043f\u044b')),
                ('breathing_rhythm', models.CharField(max_length=150, verbose_name='\u0427\u0438\u0441\u043b\u043e \u0434\u044b\u0445\u0430\u043d\u0438\u0439 \u0432 \u043c\u0438\u043d\u0443\u0442\u0443')),
                ('history', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalhistory.HistoryPatientLife')),
            ],
            options={
                'db_table': 'respiratory_system',
                'verbose_name': '\u0421\u0438\u0441\u0442\u0435\u043c\u0430 \u0434\u044b\u0445\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0421\u0438\u0441\u0442\u0435\u043c\u0430 \u0434\u044b\u0445\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Senses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senses', models.CharField(blank=True, max_length=150, verbose_name='\u041e\u0440\u0433\u0430\u043d\u044b \u0447\u0443\u0441\u0442\u0432')),
                ('eyes', models.CharField(blank=True, max_length=150, verbose_name='\u0413\u043b\u0430\u0437\u0430')),
                ('hearing', models.CharField(blank=True, max_length=150, verbose_name='\u0421\u043b\u0443\u0445')),
                ('skin_sensitivity', models.CharField(blank=True, max_length=150, verbose_name='\u0427\u0443\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u043a\u043e\u0436\u043d\u044b\u0445 \u043f\u043e\u043a\u0440\u043e\u0432\u043e\u0432')),
                ('smell', models.CharField(blank=True, max_length=150, verbose_name='\u041e\u0431\u043e\u043d\u044f\u043d\u0438\u0435')),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medicalhistory.HistoryPatientLife')),
            ],
            options={
                'db_table': 'senses',
                'verbose_name': '\u041e\u0440\u0433\u0430\u043d\u044b \u0447\u0443\u0432\u0441\u0442\u0432 \u0431\u043e\u043b\u044c\u043d\u043e\u0433\u043e',
                'verbose_name_plural': '\u041e\u0440\u0433\u0430\u043d\u044b \u0447\u0443\u0432\u0441\u0442\u0432 \u0431\u043e\u043b\u044c\u043d\u043e\u0433\u043e',
            },
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(blank=True, max_length=100, verbose_name='\u0422\u0438\u043f \u043a\u043e\u0436\u0438')),
            ],
            options={
                'db_table': 'skin_types',
            },
        ),
        migrations.CreateModel(
            name='StatusLocalis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outpatient_studies', models.TextField(verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435 \u0430\u043c\u0431\u0443\u043b\u0430\u0442\u043e\u0440\u043d\u043e\u0433\u043e \u0438\u0441\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('date_doctor', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0440\u0430\u0447\u0430')),
                ('history', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalhistory.HistoryPatientLife')),
            ],
            options={
                'db_table': 'status_localis',
                'verbose_name': '\u0421\u0442\u0430\u0442\u0443\u0441 \u043b\u043e\u043a\u0430\u043b\u0438\u0441',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441 \u043b\u043e\u043a\u0430\u043b\u0438\u0441',
            },
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menstruation_ache', models.CharField(blank=True, choices=[('\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0435', '\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0435'), ('\u043d\u0435\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0435', '\u043d\u0435\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0435')], max_length=50, null=True, verbose_name='\u041c\u0435\u0441\u044f\u0447\u043d\u044b\u0435(\u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043e\u0441\u0442\u044c)')),
                ('mensrtuation_regularity', models.CharField(blank=True, choices=[('\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0435', '\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0435'), ('\u043d\u0435\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0435', '\u043d\u0435\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0435')], max_length=50, null=True, verbose_name='\u041c\u0435\u0441\u044f\u0447\u043d\u044b\u0435(\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u043e\u0441\u0442\u044c)')),
                ('menstruation_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041c\u0435\u0441\u044f\u0447\u043d\u044b\u0435(\u0441 \u043b\u0435\u0442)')),
                ('climax_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041a\u043b\u0438\u043c\u0430\u043a\u0441(\u0441 \u043b\u0435\u0442)')),
                ('pregnancy_count', models.PositiveIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u0431\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0441\u0442\u0435\u0439')),
                ('childbirth_count', models.PositiveIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u0440\u043e\u0434\u043e\u0432')),
                ('miscarriages_count', models.PositiveIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u0432\u044b\u043a\u0438\u0434\u044b\u0448\u0435\u0439')),
                ('pregnancy_proceeds', models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u0447\u0435\u043d\u0438\u0435 \u0431\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0441\u0442\u0438')),
                ('mammary_gland', models.TextField(blank=True, null=True, verbose_name='\u041c\u043e\u043b\u043e\u0447\u043d\u044b\u0435 \u0436\u0435\u043b\u0435\u0437\u044b')),
                ('history', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalhistory.HistoryPatientLife')),
            ],
            options={
                'db_table': 'women',
                'verbose_name': '\u0423 \u0436\u0435\u043d\u0449\u0438\u043d',
                'verbose_name_plural': '\u0423 \u0436\u0435\u043d\u0449\u0438\u043d',
            },
        ),
        migrations.AddField(
            model_name='historypatientlife',
            name='infection',
            field=models.ManyToManyField(blank=True, related_name='infections', to='medicalhistory.Infection', verbose_name='\u0418\u043d\u0444\u0435\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0435 \u0437\u0430\u0431\u043e\u043b\u0435\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='genitourinarysystem',
            name='history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalhistory.HistoryPatientLife'),
        ),
        migrations.AddField(
            model_name='endocrinesystem',
            name='history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalhistory.HistoryPatientLife'),
        ),
        migrations.AddField(
            model_name='digestivesystem',
            name='history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalhistory.HistoryPatientLife'),
        ),
        migrations.AddField(
            model_name='cardiovascularsystem',
            name='history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalhistory.HistoryPatientLife'),
        ),
    ]
