# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypatientlife',
            name='alcohol_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u0423\u043f\u043e\u0442\u0440\u0435\u0431\u043b\u0435\u043d\u0438\u0435 \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044f(\u0432\u043e\u0437\u0440\u0430\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='historypatientlife',
            name='smoking_packs_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041a\u0443\u0440\u0435\u043d\u0438\u0435 \u043f\u0430\u0447\u0435\u043a \u0432 \u0434\u0435\u043d\u044c'),
        ),
        migrations.AlterField(
            model_name='historypatientlife',
            name='smoking_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041a\u0443\u0440\u0435\u043d\u0438\u0435 (\u0441 \u043b\u0435\u0442)'),
        ),
        migrations.AlterField(
            model_name='women',
            name='childbirth_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u0440\u043e\u0434\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='women',
            name='climax_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041a\u043b\u0438\u043c\u0430\u043a\u0441(\u0441 \u043b\u0435\u0442)'),
        ),
        migrations.AlterField(
            model_name='women',
            name='menstruation_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041c\u0435\u0441\u044f\u0447\u043d\u044b\u0435(\u0441 \u043b\u0435\u0442)'),
        ),
        migrations.AlterField(
            model_name='women',
            name='miscarriages_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u0432\u044b\u043a\u0438\u0434\u044b\u0448\u0435\u0439'),
        ),
        migrations.AlterField(
            model_name='women',
            name='pregnancy_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u0431\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0441\u0442\u0435\u0439'),
        ),
    ]
