# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0002_auto_20160610_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respiratorysystem',
            old_name='nasal_breathing_type',
            new_name='nasal_breathing',
        ),
        migrations.AlterField(
            model_name='respiratorysystem',
            name='breathing_rhythm',
            field=models.CharField(max_length=150, verbose_name='\u0420\u0438\u0442\u043c \u0434\u044b\u0445\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='respiratorysystem',
            name='number_breaths_perminute',
            field=models.CharField(max_length=150, verbose_name='\u0427\u0438\u0441\u043b\u043e \u0434\u044b\u0445\u0430\u043d\u0438\u0439 \u0432 \u043c\u0438\u043d\u0443\u0442\u0443'),
        ),
        migrations.AlterField(
            model_name='respiratorysystem',
            name='wheezing',
            field=models.CharField(max_length=150, verbose_name='\u0425\u0440\u0438\u043f\u044b'),
        ),
    ]
