# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 09:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0003_auto_20160610_0905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BodyType',
        ),
        migrations.DeleteModel(
            name='BonesType',
        ),
        migrations.DeleteModel(
            name='JointsType',
        ),
        migrations.DeleteModel(
            name='LymphNodeType',
        ),
        migrations.DeleteModel(
            name='MusclesType',
        ),
        migrations.DeleteModel(
            name='NailsType',
        ),
        migrations.DeleteModel(
            name='PositionType',
        ),
        migrations.DeleteModel(
            name='SkinType',
        ),
        migrations.RenameField(
            model_name='cardiovascularsystem',
            old_name='myosphhygmia',
            new_name='pulse_deficit',
        ),
        migrations.RenameField(
            model_name='cardiovascularsystem',
            old_name='viens',
            new_name='vien',
        ),
        migrations.AlterField(
            model_name='cardiovascularsystem',
            name='epigastric_pulsation',
            field=models.CharField(max_length=150, verbose_name='\u042d\u043f\u0438\u0433\u0430\u0441\u0442\u0440\u0430\u043b\u044c\u043d\u0430\u044f \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='cardiovascularsystem',
            name='pulse_rhythm',
            field=models.CharField(max_length=150, verbose_name='\u041f\u0443\u043b\u044c\u0441-\u0420\u0438\u0442\u043c'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='disease',
            field=models.TextField(verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u0440\u0430\u0432\u043c\u044b'),
        ),
        migrations.AlterField(
            model_name='historypatientlife',
            name='alcohol_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='\u0423\u043f\u043e\u0442\u0440\u0435\u0431\u043b\u0435\u043d\u0438\u0435 \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044f(\u0432\u043e\u0437\u0440\u0430\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='historypatientlife',
            name='disability_group',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '\u041f\u0435\u0440\u0432\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430'), (2, '\u0412\u0442\u043e\u0440\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430'), (3, '\u0422\u0440\u0435\u0442\u044c\u044f \u0433\u0440\u0443\u043f\u043f\u0430')], validators=[django.core.validators.MaxValueValidator(3)], verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0438\u043d\u0432\u0430\u043b\u0438\u0434\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='historypatientlife',
            name='retired',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='\u041d\u0430 \u043f\u0435\u043d\u0441\u0438\u0438 (\u0432\u043e\u0437\u0440\u0430\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='historypatientlife',
            name='smoking_packs_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='\u041a\u0443\u0440\u0435\u043d\u0438\u0435 \u043f\u0430\u0447\u0435\u043a \u0432 \u0434\u0435\u043d\u044c'),
        ),
        migrations.AlterField(
            model_name='historypatientlife',
            name='smoking_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='\u041a\u0443\u0440\u0435\u043d\u0438\u0435 (\u0441 \u043b\u0435\u0442)'),
        ),
        migrations.AlterField(
            model_name='patientconditionsnow',
            name='height',
            field=models.FloatField(blank=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='\u0420\u043e\u0441\u0442(\u043c.)'),
        ),
        migrations.AlterField(
            model_name='patientconditionsnow',
            name='weight',
            field=models.FloatField(blank=True, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='\u0412\u0435\u0441(\u043a\u0433.)'),
        ),
        migrations.AlterField(
            model_name='women',
            name='childbirth_count',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='\u0427\u0438\u0441\u043b\u043e \u0440\u043e\u0434\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='women',
            name='climax_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='\u041a\u043b\u0438\u043c\u0430\u043a\u0441(\u0441 \u043b\u0435\u0442)'),
        ),
        migrations.AlterField(
            model_name='women',
            name='menstruation_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='\u041c\u0435\u0441\u044f\u0447\u043d\u044b\u0435(\u0441 \u043b\u0435\u0442)'),
        ),
        migrations.AlterField(
            model_name='women',
            name='miscarriages_count',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='\u0427\u0438\u0441\u043b\u043e \u0432\u044b\u043a\u0438\u0434\u044b\u0448\u0435\u0439'),
        ),
        migrations.AlterField(
            model_name='women',
            name='pregnancy_count',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='\u0427\u0438\u0441\u043b\u043e \u0431\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0441\u0442\u0435\u0439'),
        ),
    ]
