# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0005_auto_20160610_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuropsychologicalsystem',
            old_name='autographism',
            new_name='dermographism',
        ),
        migrations.AlterField(
            model_name='statuslocalis',
            name='date_doctor',
            field=models.DateField(default=datetime.datetime(2016, 6, 10, 15, 59, 30, 979381), verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0440\u0430\u0447\u0430'),
        ),
    ]
