# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0006_auto_20160610_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslocalis',
            name='date_doctor',
            field=models.DateField(default=datetime.datetime(2016, 6, 10, 16, 8, 44, 41560), verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0440\u0430\u0447\u0430'),
        ),
        migrations.AlterField(
            model_name='women',
            name='menstruation_ache',
            field=models.CharField(blank=True, choices=[('\u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043d\u043e', '\u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043d\u043e'), ('\u043d\u0435\u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043d\u043e', '\u043d\u0435\u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043d\u043e')], max_length=50, null=True, verbose_name='\u041c\u0435\u0441\u044f\u0447\u043d\u044b\u0435(\u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043e\u0441\u0442\u044c)'),
        ),
    ]
