# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 11:15
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0007_auto_20160610_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respiratorysystem',
            name='number_breaths_perminute',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='\u0427\u0438\u0441\u043b\u043e \u0434\u044b\u0445\u0430\u043d\u0438\u0439 \u0432 \u043c\u0438\u043d\u0443\u0442\u0443'),
        ),
        migrations.AlterField(
            model_name='statuslocalis',
            name='date_doctor',
            field=models.DateField(default=datetime.datetime(2016, 6, 10, 17, 15, 12, 607498), verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0440\u0430\u0447\u0430'),
        ),
    ]
