# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 12:09
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0009_auto_20160610_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiovascularsystem',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='cardiovascularsystem',
            name='blood_pressure_bottom',
            field=models.PositiveSmallIntegerField(default=1, max_length=150, validators=[django.core.validators.MaxValueValidator(110)], verbose_name='\u0410\u0440\u0442\u0435\u0440\u0438\u0430\u043b\u044c\u043d\u043e\u0435 \u0434\u0430\u0432\u043b\u0435\u043d\u0438\u0435(\u043d\u0438\u0436\u043d\u0435\u0435,\u043c\u043c.\u0440\u0442.\u0441\u0442.))'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardiovascularsystem',
            name='blood_pressure_top',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='\u0410\u0440\u0442\u0435\u0440\u0438\u0430\u043b\u044c\u043d\u043e\u0435 \u0434\u0430\u0432\u043b\u0435\u043d\u0438\u0435(\u0432\u0435\u0440\u0445\u043d\u0435\u0435, \u043c\u043c.\u0440\u0442.\u0441\u0442.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genitourinarysystem',
            name='urination_color',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0426\u0432\u0435\u0442 \u043c\u043e\u0447\u0438'),
        ),
        migrations.AddField(
            model_name='genitourinarysystem',
            name='urination_quan',
            field=models.CharField(max_length=150, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e(\u0441\u043e \u0441\u043b\u043e\u0432 \u043f\u0430\u0446\u0438\u0435\u043d\u0442\u0430)'),
        ),
        migrations.AlterField(
            model_name='cardiovascularsystem',
            name='frequency',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='\u0427\u0430\u0441\u0442\u043e\u0442\u0430-\u041f\u0443\u043b\u044c\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='bl_consistency',
            field=models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u043a\u043e\u043d\u0441\u0438\u0441\u0442\u0435\u043d\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='bl_surface',
            field=models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='bl_tenderness',
            field=models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='bottom_line',
            field=models.CharField(max_length=150, verbose_name='\u043d\u0438\u0436\u043d\u044f\u044f \u0433\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='boundaries',
            field=models.CharField(max_length=150, verbose_name='\u0413\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='consistency',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u043a\u043e\u043d\u0441\u0438\u0441\u0442\u0435\u043d\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='left_costal_arch',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u043b\u0435\u0432\u043e\u0439 \u0440\u0435\u0431\u0435\u0440\u043d\u043e\u0439 \u0434\u0443\u0433\u0435'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='liver',
            field=models.CharField(max_length=150, verbose_name='\u041f\u0415\u0427\u0415\u041d\u042c(\u041f\u043e \u041a\u0443\u0440\u043b\u043e\u0432\u0443)'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='lower_midclavicularline',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u043d\u0438\u0436\u043d\u044f\u044f \u043f\u043e \u0441\u0440\u0435\u0434\u043d\u0435\u043a\u043b\u044e\u0447\u0438\u0447\u043d\u043e\u0439 \u043b\u0438\u043d\u0438\u0438 '),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='on_palpation_edbe',
            field=models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043a\u0440\u0430\u044f'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='palpation_edge',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043a\u0440\u0430\u044f'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='soreness',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='digestivesystem',
            name='surface',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='genitourinarysystem',
            name='genitals',
            field=models.TextField(null=True, verbose_name='\u041f\u043e\u043b\u043e\u0432\u044b\u0435 \u043e\u0440\u0433\u0430\u043d\u044b'),
        ),
        migrations.AlterField(
            model_name='genitourinarysystem',
            name='palpation_kidneys',
            field=models.CharField(max_length=150, null=True, verbose_name='\u041f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u044f \u043f\u043e\u0447\u0435\u043a'),
        ),
        migrations.AlterField(
            model_name='genitourinarysystem',
            name='symptoms_tapping_edge_12',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0421\u0438\u043c\u043f\u0442\u043e\u043c\u044b \u043f\u043e\u043a\u0430\u043b\u044b\u0432\u0430\u043d\u0438\u044f \u043f\u043e  \u0440\u0435\u0431\u0440\u0443'),
        ),
        migrations.AlterField(
            model_name='genitourinarysystem',
            name='urinary_bladder',
            field=models.CharField(max_length=150, null=True, verbose_name='\u041c\u043e\u0447\u0435\u0432\u043e\u0439 \u043f\u0443\u0437\u044b\u0440\u044c'),
        ),
        migrations.AlterField(
            model_name='genitourinarysystem',
            name='urination',
            field=models.CharField(max_length=150, null=True, verbose_name='\u041c\u043e\u0447\u0435\u0438\u0441\u043f\u0443\u0441\u043a\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='neuropsychologicalsystem',
            name='muscle_strength',
            field=models.CharField(max_length=150, null=True, verbose_name='\u041c\u044b\u0448\u0435\u0447\u043d\u0430\u044f \u0441\u0438\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='neuropsychologicalsystem',
            name='muscle_tone',
            field=models.CharField(max_length=150, null=True, verbose_name='\u041c\u044b\u0448\u0435\u0447\u043d\u044b\u0439 \u0442\u043e\u043d\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='neuropsychologicalsystem',
            name='parkinsonism_syndrome',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0421\u0438\u043d\u0434\u0440\u043e\u043c \u041f\u0430\u0440\u043a\u0438\u043d\u0441\u043e\u043d\u0438\u0437\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='neuropsychologicalsystem',
            name='sensitivity',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0427\u0443\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='neuropsychologicalsystem',
            name='superficial_deepreflexes',
            field=models.CharField(max_length=150, null=True, verbose_name='\u041f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u043d\u044b\u0435 \u0438 \u0433\u043b\u0443\u0431\u043e\u043a\u0438\u0435 \u0440\u0435\u0444\u043b\u0435\u043a\u0441\u044b'),
        ),
        migrations.AlterField(
            model_name='statuslocalis',
            name='date_doctor',
            field=models.DateField(default=datetime.datetime(2016, 6, 10, 18, 9, 6, 913706), verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0440\u0430\u0447\u0430'),
        ),
    ]
