# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0017_auto_20160613_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respiratorysystem',
            old_name='participation_breathing_muscle',
            new_name='part_breathing_muscle',
        ),
    ]
