# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0018_auto_20160613_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respiratorysystem',
            old_name='participaton_chest_breathing',
            new_name='part_chest_breathing',
        ),
    ]
