# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 08:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0019_auto_20160613_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiovascularsystem',
            name='blood_pressure_bottom',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(110)], verbose_name='\u0410\u0440\u0442\u0435\u0440\u0438\u0430\u043b\u044c\u043d\u043e\u0435 \u0434\u0430\u0432\u043b\u0435\u043d\u0438\u0435(\u043d\u0438\u0436\u043d\u0435\u0435,\u043c\u043c.\u0440\u0442.\u0441\u0442.))'),
        ),
    ]
