# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0020_auto_20160613_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respiratorysystem',
            old_name='number_breaths_perminute',
            new_name='count_breaths_perminute',
        ),
        migrations.RenameField(
            model_name='respiratorysystem',
            old_name='mobility_bottom_edbe_lungs',
            new_name='mobility_bottom_lungs',
        ),
        migrations.AlterField(
            model_name='respiratorysystem',
            name='auscultation_lungs',
            field=models.CharField(max_length=150, verbose_name='\u0410\u0443\u0441\u043a\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u044f \u043b\u0435\u0433\u043a\u0438\u0445:\u0434\u044b\u0445\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='respiratorysystem',
            name='omision_lower_bound',
            field=models.CharField(choices=[('\u0433\u0440\u0430\u043d\u0438\u0446\u044b \u0432 \u043d\u043e\u0440\u043c\u0435', '\u043e\u0434\u0438\u043d\u0430\u043a\u043e\u0432\u043e\u0435 \u0441 \u043e\u0431\u0435\u0438\u0445 \u0441\u0442\u043e\u0440\u043e\u043d'), ('\u043e\u043f\u0443\u0449\u0435\u043d\u043e \u043d\u0430 \u043e\u0434\u043d\u043e \u0440\u0435\u0431\u0440\u043e', '\u043e\u043f\u0443\u0449\u0435\u043d\u043e \u043d\u0430 \u043e\u0434\u043d\u043e \u0440\u0435\u0431\u0440\u043e'), ('\u043e\u043f\u0443\u0449\u0435\u043d\u043e \u043d\u0430 \u0434\u0432\u0430 \u0440\u0435\u0431\u0440\u0430', '\u043e\u043f\u0443\u0449\u0435\u043d\u043e \u043d\u0430 \u0434\u0432\u0430 \u0440\u0435\u0431\u0440\u0430')], max_length=150, verbose_name='\u041e\u043f\u0443\u0449\u0435\u043d\u0438\u0435 \u043d\u0438\u0436\u043d\u0438\u0445 \u0433\u0440\u0430\u043d\u0438\u0446'),
        ),
    ]
