# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0022_auto_20160613_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiovascularsystem',
            name='between_ribs',
        ),
    ]
