# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0027_auto_20160615_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypatientlife',
            name='disease',
            field=models.ManyToManyField(blank=True, related_name='diseases', to='mkb.ClassMKB', verbose_name='\u0422\u0440\u0430\u0432\u043c\u044b \u0438 \u0431\u043e\u043b\u0435\u0437\u043d\u0438'),
        ),
        migrations.AlterField(
            model_name='historypatientlife',
            name='infection',
            field=models.ManyToManyField(blank=True, related_name='infections', to='mkb.ClassMKB', verbose_name='\u0418\u043d\u0444\u0435\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0435 \u0437\u0430\u0431\u043e\u043b\u0435\u0432\u0430\u043d\u0438\u044f'),
        ),
    ]
