# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KIF', '0003_auto_20160613_1051'),
        ('medicalhistory', '0029_auto_20160615_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historypatientlife',
            name='patient',
        ),
        migrations.AddField(
            model_name='historypatientlife',
            name='recordpatient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u041f\u0430\u0446\u0438\u0435\u043d\u0442'),
            preserve_default=False,
        ),
    ]
