# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 08:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0034_auto_20160619_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypatientlife',
            name='disability_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '\u041f\u0435\u0440\u0432\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430'), (2, '\u0412\u0442\u043e\u0440\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430'), (3, '\u0422\u0440\u0435\u0442\u044c\u044f \u0433\u0440\u0443\u043f\u043f\u0430')], validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(4)], verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0438\u043d\u0432\u0430\u043b\u0438\u0434\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='historypatientlife',
            name='smoking_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(4)], verbose_name='\u041a\u0443\u0440\u0435\u043d\u0438\u0435 (\u0441 \u043b\u0435\u0442)'),
        ),
        migrations.AlterField(
            model_name='senses',
            name='senses_cond',
            field=models.CharField(blank=True, max_length=150, verbose_name='\u041e\u0440\u0433\u0430\u043d\u044b \u0447\u0443\u0441\u0432\u0442\u0432(\u043e\u0431\u0449\u0435\u0435 \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435)'),
        ),
    ]
