# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0035_auto_20160619_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestivesystem',
            name='stools',
            field=models.CharField(choices=[('\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0439', '\u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0439'), ('\u0437\u0430\u043f\u043e\u0440\u044b', '\u0437\u0430\u043f\u043e\u0440\u044b'), ('\u0436\u0438\u0434\u043a\u0438\u0439', '\u0436\u0438\u0434\u043a\u0438\u0439')], max_length=150, verbose_name='\u0421\u0442\u0443\u043b (\u0441\u043e \u0441\u043b\u043e\u0432 \u043f\u0430\u0446\u0438\u0435\u043d\u0442\u0430)'),
        ),
    ]
