# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 14:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0038_auto_20160619_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypatientlife',
            name='disability_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '\u041f\u0435\u0440\u0432\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430'), (2, '\u0412\u0442\u043e\u0440\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430'), (3, '\u0422\u0440\u0435\u0442\u044c\u044f \u0433\u0440\u0443\u043f\u043f\u0430')], validators=[django.core.validators.MaxValueValidator(3)], verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0438\u043d\u0432\u0430\u043b\u0438\u0434\u043d\u043e\u0441\u0442\u0438'),
        ),
    ]
