# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KIF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptDate', models.DateTimeField(verbose_name='\u0412\u0440\u0435\u043c\u0447\u044f \u043f\u0440\u0438\u043d\u044f\u0442\u0438\u044f \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432')),
                ('amount', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u044b\u043f\u0438\u0432\u0448\u0438\u0445 \u043f\u0440\u0435\u043f\u0430\u0440\u0430\u0442\u043e\u0432')),
            ],
            options={
                'db_table': 'acceptancelist',
                'verbose_name_plural': '\u0412\u0440\u0435\u043c\u044f \u043f\u0440\u0438\u043d\u044f\u0442\u0438\u044f \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432',
            },
        ),
        migrations.CreateModel(
            name='AppointmentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionDrinkDrug', models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('beginAppointment', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f')),
                ('endAppointment', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043c\u0435\u043d\u044b')),
                ('sourceDrug', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432')),
                ('amount', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u0435\u043f\u0430\u0440\u0430\u0442\u043e\u0432')),
                ('drugAl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Drug', verbose_name='\u041b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u043e')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u041f\u0430\u0446\u0438\u0435\u043d\u0442')),
            ],
            options={
                'db_table': 'appointmentlist',
                'verbose_name_plural': '\u041b\u0438\u0441\u0442 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='StockTacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('amount', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432')),
                ('rest', models.IntegerField(verbose_name='\u041c\u0430\u043d\u0443\u043f\u0443\u043b\u044f\u0446\u0438\u044f \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e\u043c')),
                ('drugSt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Drug', verbose_name='\u041b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u043e')),
            ],
            options={
                'db_table': 'stocktacking',
                'verbose_name_plural': '\u0423\u0447\u0435\u0442 \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432',
            },
        ),
        migrations.AddField(
            model_name='acceptancelist',
            name='appointmentList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.AppointmentList'),
        ),
    ]
