# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KIF', '0003_auto_20160613_1051'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktacking',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.Doctor', verbose_name='\u0410\u043f\u0442\u0435\u043a\u0430\u0440\u044c'),
        ),
    ]
