# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KIF', '0005_auto_20160617_0050'),
        ('pharmacy', '0002_stocktacking_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentlist',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.Doctor', verbose_name='\u0414\u043e\u043a\u0442\u043e\u0440'),
        ),
    ]
