# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classmkb',
            options={'verbose_name': '\u041c\u0435\u0436\u0434\u0443\u043d\u0430\u0440\u043e\u0434\u043d\u0430\u044f \u043a\u043b\u0430\u0441\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u0439', 'verbose_name_plural': '\u041c\u0435\u0436\u0434\u0443\u043d\u0430\u0440\u043e\u0434\u043d\u0430\u044f \u043a\u043b\u0430\u0441\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u0439'},
        ),
        migrations.AlterField(
            model_name='classmkb',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='classmkb',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u041a\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='classmkb',
            name='name',
            field=models.CharField(max_length=512, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='classmkb',
            name='node_count',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432 \u0433\u0440\u0443\u043f\u043f\u0435'),
        ),
        migrations.AlterField(
            model_name='classmkb',
            name='parent_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041a\u043e\u0434 \u043f\u0440\u0435\u0434\u043a\u0430'),
        ),
    ]
