# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Analyze', '0001_initial'),
        ('KIF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urineanalysis',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Doctor', verbose_name='\u0414\u043e\u043a\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='urineanalysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u041f\u0430\u0446\u0438\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='ptianalysis',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Doctor', verbose_name='\u0414\u043e\u043a\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='ptianalysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u041f\u0430\u0446\u0438\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='genbloodanalyse',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Doctor', verbose_name='\u0414\u043e\u043a\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='genbloodanalyse',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u041f\u0430\u0446\u0438\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='bloodchemistry',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Department', verbose_name='\u041e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='bloodchemistry',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Doctor', verbose_name='\u0414\u043e\u043a\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='bloodchemistry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u041f\u0430\u0446\u0438\u0435\u043d\u0442'),
        ),
    ]
