# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mkb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_area', models.CharField(max_length=100, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c')),
            ],
            options={
                'db_table': 'Area',
                'verbose_name_plural': '\u041e\u0431\u043b\u0430\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='CauseIllness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cill', models.CharField(max_length=255, verbose_name='\u043d\u0435\u0447\u0430\u0441\u0442\u043d\u044b\u0445 \u0441\u043b\u0443\u0447\u0430\u0435\u0432')),
            ],
            options={
                'db_table': 'CauseIllness',
                'verbose_name_plural': '\u041d\u0435\u0441\u0447\u0430\u0441\u0442\u043d\u044b\u0445 \u0441\u043b\u0443\u0447\u0430\u0435\u0432',
            },
        ),
        migrations.CreateModel(
            name='CheckedAnalyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pediculosis', models.BooleanField(verbose_name='\u041f\u0435\u0434\u0438\u043a\u0443\u043b\u0435\u0437')),
                ('scabies', models.BooleanField(verbose_name='\u0427\u0435\u0441\u043e\u0442\u043a\u0430')),
                ('helminthic_invasion', models.BooleanField(verbose_name='\u0433\u043b\u0438\u0441\u0442\u043d\u043e\u0439 \u0438\u043d\u0432\u0430\u0437\u0438\u0438')),
                ('Wasser_react', models.BooleanField(verbose_name='\u0440\u0435\u0430\u0446\u0438\u044f \u0412\u0430\u0441\u0441\u0435\u0440\u043c\u0430\u043d\u0430')),
                ('flyurografiya', models.BooleanField(verbose_name='\u0424\u043b\u044e\u043e\u0440\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
                ('alcohol', models.BooleanField(verbose_name='\u0410\u043b\u043a\u043e\u0433\u043e\u043b\u044c')),
                ('botkin', models.BooleanField(verbose_name='\u0411\u043e\u0442\u043a\u0438\u043d')),
                ('chi', models.BooleanField(verbose_name='\u041e\u041c\u0421')),
                ('hospit_mode', models.BooleanField(verbose_name='\u0441 \u0440\u0435\u0436\u0438\u043c\u043e\u043c \u043e\u0437\u043d\u0430\u043a\u043e\u043c\u043b\u0435\u043d')),
                ('notified_bodies_MVD', models.BooleanField(verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u043e \u043e\u0440\u0433\u0430\u043d\u0430\u043c \u041c\u0412\u0414')),
            ],
            options={
                'db_table': 'CheckedAnalyze',
                'verbose_name_plural': '\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e',
            },
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_citiz', models.CharField(max_length=100, verbose_name='\u0413\u0440\u0430\u0436\u0434\u0430\u043d\u0441\u0442\u0432\u043e')),
            ],
            options={
                'db_table': 'Citizenship',
                'verbose_name_plural': '\u0413\u0440\u0430\u0436\u0434\u0430\u043d\u0441\u0442\u0432\u043e',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dept', models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f \u043e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u044f')),
                ('count_ward', models.IntegerField(verbose_name='\u041e\u0431\u0449\u0430\u044f \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0430\u043b\u0430\u0442')),
            ],
            options={
                'db_table': 'Department',
                'verbose_name_plural': '\u041e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_diag_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('final_clinical_diag_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('clinical_diag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_diagnose', to='mkb.ClassMKB', verbose_name='\u0414\u0438\u0430\u0433\u043d\u043e\u0437 \u043a\u043b\u0438\u043d\u0438\u0447\u0435\u0441\u043a\u0438\u0439')),
            ],
            options={
                'db_table': 'Diagnosis',
                'verbose_name_plural': '\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0435 \u0434\u0438\u0430\u0433\u043d\u043e\u0437\u0430',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_doc', models.CharField(max_length=255, verbose_name='\u0424.\u0418.\u041e')),
                ('date_born_doc', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('data_start_career', models.DateField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u043e \u043a\u0430\u0440\u044c\u0435\u0440\u044b')),
                ('address', models.CharField(max_length=70, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('telephone', models.CharField(max_length=70, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.Department', verbose_name='\u041e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u0435')),
                ('loginDoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041b\u043e\u0433\u0438\u043d')),
            ],
            options={
                'verbose_name_plural': '\u0412\u0440\u0430\u0447',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_drug', models.CharField(max_length=100, verbose_name='\u041b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u043e')),
            ],
            options={
                'db_table': 'drug',
                'verbose_name_plural': '\u041b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u043e',
            },
        ),
        migrations.CreateModel(
            name='EffectsDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionDrugs', models.CharField(max_length=255, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0431\u043e\u0447\u043d\u043e\u0435')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Drug', verbose_name='\u041b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u043e')),
            ],
            options={
                'db_table': 'EffectsDrugs',
                'verbose_name_plural': '\u041f\u043e\u0431\u043e\u0447\u043d\u044b\u0435 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044f \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432',
            },
        ),
        migrations.CreateModel(
            name='ForDisabled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VOV_dsbld', models.BooleanField(verbose_name='\u0418\u041e\u0412')),
                ('desc_dsbld', models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0438\u043d\u0432\u0430\u043b\u0438\u0434\u043d\u043e\u0441\u0442\u0438')),
                ('year_dsbld', models.DateField(blank=True, null=True, verbose_name='\u0413\u043e\u0434 \u0438\u043d\u0432\u0430\u043b\u0438\u0434\u043d\u043e\u0441\u0442\u0438')),
                ('group_dsbld', models.SmallIntegerField(blank=True, null=True, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0438\u043d\u0432\u0430\u043b\u0438\u0434\u043d\u043e\u0441\u0442\u0438')),
            ],
            options={
                'db_table': 'ForDisabled',
                'verbose_name_plural': '\u0418\u043d\u0432\u0430\u043b\u0438\u0434\u043d\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hospit', models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f \u0431\u043e\u043b\u044c\u043d\u0438\u0446\u044b')),
            ],
            options={
                'db_table': 'Hospital',
                'verbose_name_plural': '\u0411\u043e\u043b\u044c\u043d\u0438\u0446\u0430',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_pat', models.CharField(max_length=100, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('name_pat', models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f')),
                ('last_name_pat', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('date_born_pat', models.DateField(verbose_name='\u0427\u0438\u0441\u043b\u043e, \u043c\u0435\u0441\u044f\u0446, \u0433\u043e\u0434 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('rhesusfactor_pat', models.CharField(max_length=10, verbose_name='\u0420\u0435\u0437\u0443\u0441 \u043f\u0440\u0438\u043d\u0430\u0434\u043b\u0435\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('bloodgroup_pat', models.CharField(choices=[('b1', '1'), ('b2', '2'), ('b3', '3'), ('b4', '4')], max_length=10, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u043a\u0440\u043e\u0432\u0438')),
                ('gender_pat', models.CharField(choices=[('ML', '\u041c\u0443\u0436\u0441\u043a\u043e\u0439'), ('FML', '\u0416\u0435\u043d\u0441\u043a\u0438\u0439')], max_length=5, verbose_name='\u041f\u043e\u043b')),
                ('num_social_protec', models.CharField(max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0443\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u0435\u043d\u0438\u044f \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0439 \u0437\u0430\u0449\u0438\u0442\u044b')),
                ('insurance_territory', models.CharField(max_length=50, verbose_name='\u0422\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u044f \u0441\u0442\u0440\u0430\u0445\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('category_pat', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043f\u0430\u0446\u0438\u0435\u043d\u0442\u0430')),
                ('retired_pat', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0443\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u0435\u043d\u0438\u044f')),
                ('place_work_pat', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041c\u0435\u0441\u0442\u043e \u0440\u0430\u0431\u043e\u0442\u044b, \u0434\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('street_pat', models.CharField(max_length=100, verbose_name='\u0423\u043b\u0438\u0446\u0430')),
                ('num_medic_record', models.IntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043c\u0435\u0434. \u043a\u0430\u0440\u0442\u044b')),
                ('login_pat', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='\u041b\u043e\u0433\u0438\u043d')),
                ('password_pat', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c')),
                ('photo_pat', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
                ('email_pat', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u044b\u0439 \u0430\u0434\u0440\u0435\u0441')),
                ('area_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='KIF.Area', verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c')),
                ('citizenship_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Citizenship', verbose_name='\u0413\u0440\u0430\u0436\u0434\u0430\u043d\u0441\u0442\u0432\u043e')),
            ],
            options={
                'db_table': 'Patient',
                'verbose_name_plural': '\u041c\u0435\u0434\u0438\u0446\u0438\u043d\u0441\u043a\u0430\u044f \u043a\u0430\u0440\u0442\u0430 \u0441\u0442\u0430\u0446\u0438\u043e\u043d\u0430\u0440\u043d\u043e\u0433\u043e \u0431\u043e\u043b\u044c\u043d\u043e\u0433\u043e',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=100, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'verbose_name_plural': '\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='RecordPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ward', models.SmallIntegerField(verbose_name='\u2116 \u043f\u0430\u043b\u0430\u0442\u044b')),
                ('receipt_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u043f\u043e\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u044f')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u0432\u044b\u043f\u0438\u0441\u043a\u0438')),
                ('admission_diag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_diagnose', to='mkb.ClassMKB', verbose_name='\u0414\u0438\u0430\u0433\u043d\u043e\u0437 \u043f\u0440\u0438 \u043f\u043e\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u0438')),
                ('dept_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='KIF.Department', verbose_name='\u041e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u0435')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.Doctor', verbose_name='\u041b\u0435\u0447\u0430\u044e\u0449\u0438\u0439 \u0432\u0440\u0430\u0447')),
                ('hospit_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Hospital', verbose_name='\u0411\u043e\u043b\u044c\u043d\u0438\u0446\u0430')),
                ('patient_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Patient', verbose_name='\u0411\u043e\u043b\u044c\u043d\u043e\u0439')),
                ('trans_dept_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_department', to='KIF.Department', verbose_name='\u041f\u0435\u0440\u0435\u0432\u0435\u0434\u0435\u043d \u0432 \u043e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'RecordPatient',
                'verbose_name_plural': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b \u0430\u043d\u0430\u043b\u0438\u0437\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reg', models.CharField(max_length=100, verbose_name='\u0420\u0430\u0439\u043e\u043d')),
                ('area_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Area', verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c')),
            ],
            options={
                'db_table': 'Region',
                'verbose_name_plural': '\u0420\u0430\u0439\u043e\u043d',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=100, verbose_name='\u0420\u043e\u043b\u044c')),
            ],
            options={
                'db_table': 'role',
                'verbose_name_plural': '\u0420\u043e\u043b\u044c',
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_send', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041a\u0435\u043c \u043d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d \u0431\u043e\u043b\u044c\u043d\u043e\u0439')),
                ('time_after_ill', models.DateTimeField(blank=True, null=True, verbose_name='\u0413\u043e\u0441\u043f\u0438\u0442\u0430\u043b\u0438\u0437\u0438\u0440\u043e\u0432\u0430\u043d \u0432 \u0431\u043e\u043b\u044c\u043d\u0438\u0446\u0443 (\u0432\u043d\u0435 \u043f\u043b\u0430\u043d\u0430) \u0441\u043f\u0443\u0441\u0438\u044f')),
                ('cause_illness_fk', models.ManyToManyField(blank=True, to='KIF.CauseIllness', verbose_name='\u043d\u0435\u0447\u0430\u0441\u0442\u043d\u044b\u0445 \u0441\u043b\u0443\u0447\u0430\u0435\u0432')),
                ('diag_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mkb.ClassMKB', verbose_name='\u0414\u0438\u0430\u0433\u043d\u043e\u0437 \u043d\u0430\u043f\u0440\u0430\u0432\u0438\u0432\u0448\u0435\u0433\u043e \u0443\u0447\u0440\u0435\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('estab_send', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.Hospital', verbose_name='\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043b\u0435\u0447\u0435\u0431\u043d\u043e\u0433\u043e \u0443\u0447\u0435\u0440\u0435\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('patient_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u0411\u043e\u043b\u044c\u043d\u043e\u0439')),
            ],
            options={
                'db_table': 'Sender',
                'verbose_name_plural': '\u041a\u0435\u043c \u0431\u044b\u043b \u043d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d \u0431\u043e\u043b\u044c\u043d\u043e\u0439',
            },
        ),
        migrations.CreateModel(
            name='StatusGradDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pd', models.CharField(max_length=100, verbose_name='\u0423\u0447\u0435\u043d\u043d\u0430\u044f \u0441\u0442\u0435\u043f\u0435\u043d\u044c')),
            ],
            options={
                'verbose_name_plural': '\u0423\u0447\u0435\u043d\u043d\u0430\u044f \u0441\u0442\u0435\u043f\u0435\u043d\u044c',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_town', models.CharField(max_length=100, verbose_name='\u0421\u0435\u043b\u043e')),
                ('region_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Region', verbose_name='\u0420\u0430\u0439\u043e\u043d')),
            ],
            options={
                'db_table': 'Town',
                'verbose_name_plural': '\u0421\u0435\u043b\u043e',
            },
        ),
        migrations.CreateModel(
            name='TypeOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tpop', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438')),
                ('data_tpop', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u043e \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438')),
                ('status_tpop', models.CharField(blank=True, choices=[('process', '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), ('end', '\u0417\u0430\u043a\u043e\u043d\u0447\u0435\u043d')], max_length=50, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('method_anesthesia', models.CharField(max_length=150, verbose_name='\u043c\u0435\u0442\u043e\u0434 \u043e\u0431\u0435\u0437\u0431\u043e\u043b\u0438\u0432\u0430\u043d\u0438\u044f')),
                ('healing_tpop', models.CharField(max_length=150, verbose_name='\u041e\u0441\u043b\u043e\u0436\u043d\u0435\u043d\u0438\u044f, \u0437\u0430\u0436\u0438\u0432\u043b\u0435\u043d\u0438\u0435')),
                ('assistant_doc', models.ManyToManyField(related_name='assistantDoc', to='KIF.Doctor', verbose_name='\u0410\u0441\u0441\u0438\u0441\u0442\u0435\u043d\u0442\u044b')),
                ('doctor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Doctor', verbose_name='\u0414\u043e\u043a\u0442\u043e\u0440')),
                ('patient_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u0411\u043e\u043b\u044c\u043d\u043e\u0439')),
            ],
            options={
                'db_table': 'TypeOperation',
                'verbose_name_plural': '\u0425\u0438\u0440\u0443\u0440\u0433\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='region_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Region', verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='patient',
            name='town_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Town', verbose_name='\u0421\u0435\u043b\u043e'),
        ),
        migrations.AddField(
            model_name='fordisabled',
            name='patient_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.Patient', verbose_name='\u0411\u043e\u043b\u044c\u043d\u043e\u0439'),
        ),
        migrations.AddField(
            model_name='effectsdrugs',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u0411\u043e\u043b\u044c\u043d\u043e\u0439'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='postDoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.Post', verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='role_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.Role', verbose_name='\u0420\u043e\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='statusPostDegree',
            field=models.ManyToManyField(to='KIF.StatusGradDegree', verbose_name='\u0423\u0447\u0435\u043d\u043d\u0430\u044f \u0441\u0442\u0435\u043f\u0435\u043d\u044c'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='clinical_diag_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_diag_doctor', to='KIF.Doctor', verbose_name='\u0424.\u0418.\u041e \u0432\u0440\u0430\u0447\u0430'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='complicatio_morbus_basalis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complicto_morbus_basalis', to='mkb.ClassMKB', verbose_name='\u043e\u0441\u043b\u043e\u0436\u043d\u0435\u043d\u0438\u0435 \u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0433\u043e \u0437\u0430\u0431\u043e\u043b\u0435\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='final_clinical_diag_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_clin_diag_doctor', to='KIF.Doctor', verbose_name='\u0424.\u0418.\u041e \u0432\u0440\u0430\u0447\u0430'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='morbus_basalis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morbus_basalis', to='mkb.ClassMKB', verbose_name='\u043e\u0441\u043d\u043e\u0432\u043d\u0430\u044f \u0431\u043e\u043b\u0435\u0437\u043d\u044c'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='morbus_concomitans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morbus_concom', to='mkb.ClassMKB', verbose_name='\u0441\u043e\u043f\u0443\u0442\u0441\u0442\u0432\u0443\u044e\u0449\u0430\u044f \u0431\u043e\u043b\u0435\u0437\u043d\u044c'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u0411\u043e\u043b\u044c\u043d\u043e\u0439'),
        ),
        migrations.AddField(
            model_name='department',
            name='hospit_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_name', to='KIF.Hospital', verbose_name='\u0418\u043c\u044f \u0431\u043e\u043b\u044c\u043d\u0438\u0446\u044b'),
        ),
        migrations.AddField(
            model_name='checkedanalyze',
            name='patient_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.RecordPatient', verbose_name='\u0411\u043e\u043b\u044c\u043d\u043e\u0439'),
        ),
    ]
