# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIF', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': '\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f \u0434\u0438\u0430\u0433\u043d\u043e\u0437\u0430'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c \u0432\u0440\u0430\u0447\u0430'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_territory',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0422\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u044f \u0441\u0442\u0440\u0430\u0445\u043e\u0432\u0430\u043d\u0438\u044f'),
        ),
    ]
