# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIF', '0002_auto_20160612_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender_pat',
            field=models.CharField(choices=[('M', '\u041c\u0443\u0436\u0441\u043a\u043e\u0439'), ('\u0416', '\u0416\u0435\u043d\u0441\u043a\u0438\u0439')], max_length=5, verbose_name='\u041f\u043e\u043b'),
        ),
    ]
