# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIF', '0003_auto_20160613_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup_pat',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u043a\u0440\u043e\u0432\u0438'),
        ),
    ]
