# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KIF', '0004_auto_20160617_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordpatient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KIF.Doctor', verbose_name='\u041b\u0435\u0447\u0430\u044e\u0449\u0438\u0439 \u0432\u0440\u0430\u0447'),
        ),
    ]
