# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadir', '0002_delete_risk_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='risk_factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='\u0424\u0430\u043a\u0442\u043e\u0440 \u0440\u0438\u0441\u043a\u0430')),
            ],
            options={
                'db_table': 'risk_factor_types',
                'verbose_name': '\u0424\u0430\u043a\u0442\u043e\u0440 \u0440\u0438\u0441\u043a\u0430',
                'verbose_name_plural': '\u0424\u0430\u043a\u0442\u043e\u0440\u044b \u0440\u0438\u0441\u043a\u0430',
            },
        ),
    ]
