# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadir', '0003_risk_factor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apical_impulse',
        ),
        migrations.DeleteModel(
            name='arteries',
        ),
        migrations.DeleteModel(
            name='auscultation_lungs',
        ),
        migrations.DeleteModel(
            name='bones',
        ),
        migrations.DeleteModel(
            name='breathing_rhythm',
        ),
        migrations.DeleteModel(
            name='cyanosis',
        ),
        migrations.DeleteModel(
            name='epigastric_pulsation',
        ),
        migrations.DeleteModel(
            name='general_state',
        ),
        migrations.DeleteModel(
            name='joints',
        ),
        migrations.DeleteModel(
            name='lymph_node',
        ),
        migrations.DeleteModel(
            name='menstruation',
        ),
        migrations.DeleteModel(
            name='mobility_bottom_lungs',
        ),
        migrations.DeleteModel(
            name='muscles',
        ),
        migrations.DeleteModel(
            name='nails',
        ),
        migrations.DeleteModel(
            name='omision_lower_bound',
        ),
        migrations.DeleteModel(
            name='percussion_lung',
        ),
        migrations.DeleteModel(
            name='pregnancy_proceeds',
        ),
        migrations.DeleteModel(
            name='pulse_deficit',
        ),
        migrations.DeleteModel(
            name='pulse_rhythm',
        ),
        migrations.DeleteModel(
            name='skin',
        ),
        migrations.DeleteModel(
            name='vien',
        ),
        migrations.DeleteModel(
            name='visible_heart_pulsation',
        ),
        migrations.DeleteModel(
            name='wheezing',
        ),
        migrations.DeleteModel(
            name='when_viewed',
        ),
    ]
