# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadir', '0004_auto_20160618_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='apical_impulse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0412\u0435\u0440\u0445\u0443\u0448\u0435\u0447\u043d\u044b\u0439 \u0442\u043e\u043b\u0447\u043e\u043a')),
            ],
            options={
                'db_table': 'apical_impulse_types',
                'verbose_name': '\u0412\u0435\u0440\u0445\u0443\u0448\u0435\u0447\u043d\u044b\u0439 \u0442\u043e\u043b\u0447\u043e\u043a',
                'verbose_name_plural': '\u0412\u0435\u0440\u0445\u0443\u0448\u0435\u0447\u043d\u044b\u0439 \u0442\u043e\u043b\u0447\u043e\u043a',
            },
        ),
        migrations.CreateModel(
            name='arteries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0410\u0440\u0442\u0435\u0440\u0438\u0438')),
            ],
            options={
                'db_table': 'arteries_types',
                'verbose_name': '\u0410\u0440\u0442\u0435\u0440\u0438\u0438',
                'verbose_name_plural': '\u0410\u0440\u0442\u0435\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='auscultation_lungs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u0435\u0440\u043a\u0443\u0441\u0441\u0438\u044f \u043b\u0435\u0433\u043a\u0438\u0445')),
            ],
            options={
                'db_table': 'auscultation_lungs_types',
                'verbose_name': '\u0410\u0443\u0441\u043a\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u044f \u043b\u0435\u0433\u043a\u0438\u0445:\u0434\u044b\u0445\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0410\u0443\u0441\u043a\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u044f \u043b\u0435\u0433\u043a\u0438\u0445:\u0434\u044b\u0445\u0430\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='bones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0422\u0438\u043f \u043a\u043e\u0441\u0442\u0435\u0439')),
            ],
            options={
                'db_table': 'bones_types',
                'verbose_name': '\u041a\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u041a\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='breathing_rhythm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u0440\u0438 \u043e\u0441\u043c\u043e\u0442\u0440\u0435')),
            ],
            options={
                'db_table': 'breathing_rhythm_types',
                'verbose_name': '\u0420\u0438\u0442\u043c \u0434\u044b\u0445\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0420\u0438\u0442\u043c \u0434\u044b\u0445\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='cyanosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0426\u0438\u0430\u043d\u043e\u0437')),
            ],
            options={
                'db_table': 'cyanosis_types',
                'verbose_name': '\u0426\u0438\u0430\u043d\u043e\u0437',
                'verbose_name_plural': '\u0426\u0438\u0430\u043d\u043e\u0437',
            },
        ),
        migrations.CreateModel(
            name='epigastric_pulsation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u042d\u043f\u0438\u0433\u0430\u0441\u0442\u0440\u0430\u043b\u044c\u043d\u0430\u044f \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u044f')),
            ],
            options={
                'db_table': 'epigastric_pulsation_types',
                'verbose_name': '\u042d\u043f\u0438\u0433\u0430\u0441\u0442\u0440\u0430\u043b\u044c\u043d\u0430\u044f \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u042d\u043f\u0438\u0433\u0430\u0441\u0442\u0440\u0430\u043b\u044c\u043d\u0430\u044f \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='general_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041e\u0431\u0449\u0435\u0435 \u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'general_state_types',
                'verbose_name': '\u041e\u0431\u0449\u0435\u0435 \u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041e\u0431\u0449\u0435\u0435 \u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='joints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0422\u0438\u043f \u0441\u0443\u0441\u0442\u0430\u0432\u043e\u0432')),
            ],
            options={
                'db_table': 'joints_types',
                'verbose_name': '\u0421\u0443\u0441\u0442\u0430\u0432\u044b',
                'verbose_name_plural': '\u0421\u0443\u0441\u0442\u0430\u0432\u044b',
            },
        ),
        migrations.CreateModel(
            name='lymph_node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041b\u0438\u043c\u0444\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0443\u0437\u043b\u044b')),
            ],
            options={
                'db_table': 'lymphnode_types',
                'verbose_name': '\u041b\u0438\u043c\u0444\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0443\u0437\u043b\u044b',
                'verbose_name_plural': '\u041b\u0438\u043c\u0444\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0443\u0437\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='menstruation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, verbose_name='\u0422\u0438\u043f \u043c\u0435\u043d\u0441\u0442\u0440\u0443\u0430\u0446\u0438\u0438')),
            ],
            options={
                'db_table': 'menstruation_types',
                'verbose_name': '\u0422\u0435\u0447\u0435\u043d\u0438\u0435 \u043c\u0435\u043d\u0441\u0442\u0440\u0443\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u0422\u0435\u0447\u0435\u043d\u0438\u0435 \u043c\u0435\u043d\u0441\u0442\u0440\u0443\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='mobility_bottom_lungs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u043e\u0434\u0432\u0438\u0436\u043d\u043e\u0441\u0442\u044c \u043d\u0438\u0436\u043d\u0435\u0433\u043e \u043a\u0440\u0430\u044f \u043b\u0435\u0433\u043a\u0438\u0445')),
            ],
            options={
                'db_table': 'mobility_bottom_lungs_types',
                'verbose_name': '\u041f\u043e\u0434\u0432\u0438\u0436\u043d\u043e\u0441\u0442\u044c \u043d\u0438\u0436\u043d\u0435\u0433\u043e \u043a\u0440\u0430\u044f \u043b\u0435\u0433\u043a\u0438\u0445',
                'verbose_name_plural': '\u041f\u043e\u0434\u0432\u0438\u0436\u043d\u043e\u0441\u0442\u044c \u043d\u0438\u0436\u043d\u0435\u0433\u043e \u043a\u0440\u0430\u044f \u043b\u0435\u0433\u043a\u0438\u0445',
            },
        ),
        migrations.CreateModel(
            name='muscles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0422\u0438\u043f \u043c\u044b\u0449\u0446\u044b')),
            ],
            options={
                'db_table': 'muscles_types',
                'verbose_name': '\u041c\u044b\u0448\u0446\u044b',
                'verbose_name_plural': '\u041c\u044b\u0448\u0446\u044b',
            },
        ),
        migrations.CreateModel(
            name='nails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0422\u0438\u043f \u043d\u043e\u0433\u0442\u0435\u0439')),
            ],
            options={
                'db_table': 'nails_types',
                'verbose_name': '\u041d\u043e\u0433\u0442\u0438',
                'verbose_name_plural': '\u041d\u043e\u0433\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='omision_lower_bound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041e\u043f\u0443\u0449\u0435\u043d\u0438\u0435 \u043d\u0438\u0436\u043d\u0438\u0445 \u0433\u0440\u0430\u043d\u0438\u0446')),
            ],
            options={
                'db_table': 'omision_lower_bound_types',
                'verbose_name': '\u041e\u043f\u0443\u0449\u0435\u043d\u0438\u0435 \u043d\u0438\u0436\u043d\u0438\u0445 \u0433\u0440\u0430\u043d\u0438\u0446',
                'verbose_name_plural': '\u041e\u043f\u0443\u0449\u0435\u043d\u0438\u0435 \u043d\u0438\u0436\u043d\u0438\u0445 \u0433\u0440\u0430\u043d\u0438\u0446',
            },
        ),
        migrations.CreateModel(
            name='percussion_lung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u0435\u0440\u043a\u0443\u0441\u0441\u0438\u044f \u043b\u0435\u0433\u043a\u0438\u0445')),
            ],
            options={
                'db_table': 'percussion_lung_types',
                'verbose_name': '\u041f\u0435\u0440\u043a\u0443\u0441\u0441\u0438\u044f \u043b\u0435\u0433\u043a\u0438\u0445',
                'verbose_name_plural': '\u041f\u0435\u0440\u043a\u0443\u0441\u0441\u0438\u044f \u043b\u0435\u0433\u043a\u0438\u0445',
            },
        ),
        migrations.CreateModel(
            name='pregnancy_proceeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0422\u0438\u043f \u043f\u0440\u043e\u0442\u0435\u043a\u0430\u043d\u0438\u044f \u0431\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0441\u0442\u0438')),
            ],
            options={
                'db_table': 'pregnancy_proceeds_types',
                'verbose_name': '\u0422\u0435\u0447\u0435\u043d\u0438\u0435 \u0431\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u0422\u0435\u0447\u0435\u043d\u0438\u0435 \u0431\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='pulse_deficit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0414\u0435\u0444\u0438\u0446\u0438\u0442 \u043f\u0443\u043b\u044c\u0441\u0430')),
            ],
            options={
                'db_table': 'pulse_deficit_types',
                'verbose_name': '\u0414\u0435\u0444\u0438\u0446\u0438\u0442 \u043f\u0443\u043b\u044c\u0441\u0430',
                'verbose_name_plural': '\u0414\u0435\u0444\u0438\u0446\u0438\u0442 \u043f\u0443\u043b\u044c\u0441\u0430',
            },
        ),
        migrations.CreateModel(
            name='pulse_rhythm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u0443\u043b\u044c\u0441-\u0420\u0438\u0442\u043c')),
            ],
            options={
                'db_table': 'pulse_rhythm_types',
                'verbose_name': '\u041f\u0443\u043b\u044c\u0441-\u0420\u0438\u0442\u043c',
                'verbose_name_plural': '\u041f\u0443\u043b\u044c\u0441-\u0420\u0438\u0442\u043c',
            },
        ),
        migrations.CreateModel(
            name='skin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='\u0422\u0438\u043f \u043a\u043e\u0436\u043d\u044b\u0445 \u043f\u043e\u043a\u0440\u043e\u0432\u043e\u0432')),
            ],
            options={
                'db_table': 'skin_types',
                'verbose_name': '\u041a\u043e\u0436\u043d\u044b\u0435 \u043f\u043e\u043a\u0440\u043e\u0432\u044b',
                'verbose_name_plural': '\u041a\u043e\u0436\u043d\u044b\u0435 \u043f\u043e\u043a\u0440\u043e\u0432\u044b',
            },
        ),
        migrations.CreateModel(
            name='vien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0412\u0435\u043d\u044b')),
            ],
            options={
                'db_table': 'vien_types',
                'verbose_name': '\u0412\u0435\u043d\u044b',
                'verbose_name_plural': '\u0412\u0435\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='visible_heart_pulsation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0412\u0438\u0434\u0438\u043c\u044b\u0435 \u043d\u0430 \u0433\u043b\u0430\u0437 \u0441\u0435\u0440\u0434\u0435\u0447\u043d\u044b\u0435 \u043f\u0443\u043b\u044c\u0441\u0430\u0446\u0438\u0438')),
            ],
            options={
                'db_table': 'visible_heart_pulsation_types',
                'verbose_name': '\u0412\u0438\u0434\u0438\u043c\u044b\u0435 \u043d\u0430 \u0433\u043b\u0430\u0437 \u0441\u0435\u0440\u0434\u0435\u0447\u043d\u044b\u0435 \u043f\u0443\u043b\u044c\u0441\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u0412\u0438\u0434\u0438\u043c\u044b\u0435 \u043d\u0430 \u0433\u043b\u0430\u0437 \u0441\u0435\u0440\u0434\u0435\u0447\u043d\u044b\u0435 \u043f\u0443\u043b\u044c\u0441\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='wheezing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0425\u0440\u0438\u043f\u044b')),
            ],
            options={
                'db_table': 'wheezing_types',
                'verbose_name': '\u0425\u0440\u0438\u043f\u044b',
                'verbose_name_plural': '\u0425\u0440\u0438\u043f\u044b',
            },
        ),
        migrations.CreateModel(
            name='when_viewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0420\u0438\u0442\u043c \u0434\u044b\u0445\u0430\u043d\u0438\u044f')),
            ],
            options={
                'db_table': 'when_viewed_types',
                'verbose_name': '\u0420\u0438\u0442\u043c \u0434\u044b\u0445\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0420\u0438\u0442\u043c \u0434\u044b\u0445\u0430\u043d\u0438\u044f',
            },
        ),
    ]
