# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadir', '0005_apical_impulse_arteries_auscultation_lungs_bones_breathing_rhythm_cyanosis_epigastric_pulsation_gene'),
    ]

    operations = [
        migrations.DeleteModel(
            name='risk_factor',
        ),
    ]
