# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadir', '0007_risk_factor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='risk_factor',
        ),
    ]
