# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadir', '0009_risk_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='eyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0413\u043b\u0430\u0437\u0430')),
            ],
            options={
                'db_table': 'eyes_types',
                'verbose_name': '\u0413\u043b\u0430\u0437\u0430',
                'verbose_name_plural': '\u0413\u043b\u0430\u0437\u0430',
            },
        ),
        migrations.CreateModel(
            name='hearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0421\u043b\u0443\u0445')),
            ],
            options={
                'db_table': 'hearing_types',
                'verbose_name': '\u0421\u043b\u0443\u0445',
                'verbose_name_plural': '\u0421\u043b\u0443\u0445',
            },
        ),
        migrations.CreateModel(
            name='mammary_gland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041c\u043e\u043b\u043e\u0447\u043d\u044b\u0435 \u0436\u0435\u043b\u0435\u0437\u044b')),
            ],
            options={
                'db_table': 'mammary_gland_types',
                'verbose_name': '\u041c\u043e\u043b\u043e\u0447\u043d\u044b\u0435 \u0436\u0435\u043b\u0435\u0437\u044b',
                'verbose_name_plural': '\u041c\u043e\u043b\u043e\u0447\u043d\u044b\u0435 \u0436\u0435\u043b\u0435\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='senses_cond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041e\u0440\u0433\u0430\u043d\u044b \u0447\u0443\u0441\u0432\u0442\u0432')),
            ],
            options={
                'db_table': 'senses_cond_types',
                'verbose_name': '\u041e\u0440\u0433\u0430\u043d\u044b \u0447\u0443\u0441\u0432\u0442\u0432',
                'verbose_name_plural': '\u041e\u0440\u0433\u0430\u043d\u044b \u0447\u0443\u0441\u0432\u0442\u0432',
            },
        ),
        migrations.CreateModel(
            name='skin_sensitivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0427\u0443\u0432\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c  \u043a\u043e\u0436\u043d\u044b\u0445 \u043f\u043e\u043a\u0440\u043e\u0432\u043e\u0432')),
            ],
            options={
                'db_table': 'skin_sensitivity_types',
                'verbose_name': '\u0427\u0443\u0432\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c  \u043a\u043e\u0436\u043d\u044b\u0445 \u043f\u043e\u043a\u0440\u043e\u0432\u043e\u0432',
                'verbose_name_plural': '\u0427\u0443\u0432\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c  \u043a\u043e\u0436\u043d\u044b\u0445 \u043f\u043e\u043a\u0440\u043e\u0432\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='smell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041e\u0431\u043e\u043d\u044f\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'smell_types',
                'verbose_name': '\u041e\u0431\u043e\u043d\u044f\u043d\u0438\u0435',
                'verbose_name_plural': '\u041e\u0431\u043e\u043d\u044f\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='subcutaneous_tissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='\u0422\u0438\u043f \u043f\u043e\u0434\u043a\u043e\u0436\u043d\u043e\u0439 \u043a\u043b\u0435\u0442\u0447\u0430\u0442\u043a\u0438')),
            ],
            options={
                'db_table': 'subcutaneous_tissue_types',
                'verbose_name': '\u0422\u0438\u043f \u043f\u043e\u0434\u043a\u043e\u0436\u043d\u043e\u0439 \u043a\u043b\u0435\u0442\u0447\u0430\u0442\u043a\u0438',
                'verbose_name_plural': '\u0422\u0438\u043f \u043f\u043e\u0434\u043a\u043e\u0436\u043d\u043e\u0439 \u043a\u043b\u0435\u0442\u0447\u0430\u0442\u043a\u0438',
            },
        ),
        migrations.AlterModelOptions(
            name='general_state',
            options={'verbose_name': '\u041e\u0431\u0449\u0435\u0435 \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435', 'verbose_name_plural': '\u041e\u0431\u0449\u0435\u0435 \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435'},
        ),
        migrations.AlterField(
            model_name='general_state',
            name='type',
            field=models.CharField(max_length=150, verbose_name='\u041e\u0431\u0449\u0435\u0435 \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435'),
        ),
    ]
