# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadir', '0010_auto_20160619_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='nasal_breathing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041d\u043e\u0441\u043e\u0432\u043e\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'nasal_breathing_types',
                'verbose_name': '\u041d\u043e\u0441\u043e\u0432\u043e\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u041d\u043e\u0441\u043e\u0432\u043e\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='part_breathing_muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0423\u0447\u0430\u0441\u0442\u0438\u0435 \u0432 \u0430\u043a\u0442\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u044f \u043c\u044b\u0448\u0446')),
            ],
            options={
                'db_table': 'part_breathing_muscle_types',
                'verbose_name': '\u0423\u0447\u0430\u0441\u0442\u0438\u0435 \u0432 \u0430\u043a\u0442\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u044f \u043c\u044b\u0448\u0446',
                'verbose_name_plural': '\u0423\u0447\u0430\u0441\u0442\u0438\u0435 \u0432 \u0430\u043a\u0442\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u044f \u043c\u044b\u0448\u0446',
            },
        ),
        migrations.CreateModel(
            name='part_chest_breathing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0423\u0447\u0430\u0441\u0442\u0438\u0435 \u0433\u0440\u0443\u0434\u043d\u043e\u0439 \u043a\u043b\u0435\u0442\u043a\u0438 \u0432 \u0430\u043a\u0442\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u044f')),
            ],
            options={
                'db_table': 'part_chest_breathing_types',
                'verbose_name': '\u0423\u0447\u0430\u0441\u0442\u0438\u0435 \u0433\u0440\u0443\u0434\u043d\u043e\u0439 \u043a\u043b\u0435\u0442\u043a\u0438 \u0432 \u0430\u043a\u0442\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0423\u0447\u0430\u0441\u0442\u0438\u0435 \u0433\u0440\u0443\u0434\u043d\u043e\u0439 \u043a\u043b\u0435\u0442\u043a\u0438 \u0432 \u0430\u043a\u0442\u0435 \u0434\u044b\u0445\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='rib_cage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0413\u0440\u0443\u0434\u043d\u0430\u044f \u043a\u043b\u0435\u0442\u043a\u0430')),
            ],
            options={
                'db_table': 'rib_cage_types',
                'verbose_name': '\u0413\u0440\u0443\u0434\u043d\u0430\u044f \u043a\u043b\u0435\u0442\u043a\u0430',
                'verbose_name_plural': '\u0413\u0440\u0443\u0434\u043d\u0430\u044f \u043a\u043b\u0435\u0442\u043a\u0430',
            },
        ),
        migrations.AlterModelOptions(
            name='when_viewed',
            options={'verbose_name': '\u041f\u0440\u0438 \u043e\u0441\u043c\u043e\u0442\u0440\u0435', 'verbose_name_plural': '\u041f\u0440\u0438 \u043e\u0441\u043c\u043e\u0442\u0440\u0435'},
        ),
        migrations.AlterField(
            model_name='auscultation_lungs',
            name='type',
            field=models.CharField(max_length=150, verbose_name='\u0410\u0443\u0441\u043a\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u044f \u043b\u0435\u0433\u043a\u0438\u0445'),
        ),
        migrations.AlterField(
            model_name='breathing_rhythm',
            name='type',
            field=models.CharField(max_length=150, verbose_name='\u0420\u0438\u0442\u043c \u0434\u044b\u0445\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='when_viewed',
            name='type',
            field=models.CharField(max_length=150, verbose_name='\u041f\u0440\u0438 \u043e\u0441\u043c\u043e\u0442\u0440\u0435'),
        ),
    ]
