# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadir', '0011_auto_20160619_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='bl_consistency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u043a\u043e\u043d\u0441\u0438\u0441\u0442\u0435\u043d\u0446\u0438\u044f')),
            ],
            options={
                'db_table': 'bl_consistency_types',
                'verbose_name': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u043a\u043e\u043d\u0441\u0438\u0441\u0442\u0435\u043d\u0446\u0438\u044f',
                'verbose_name_plural': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u043a\u043e\u043d\u0441\u0438\u0441\u0442\u0435\u043d\u0446\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='bl_surface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'db_table': 'bl_surface_types',
                'verbose_name': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='bl_tenderness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'db_table': 'bl_tenderness_types',
                'verbose_name': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043d\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='bottom_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043d\u0438\u0436\u043d\u044f\u044f \u0433\u0440\u0430\u043d\u0438\u0446\u0430')),
            ],
            options={
                'db_table': 'bottom_line_types',
                'verbose_name': '\u043d\u0438\u0436\u043d\u044f\u044f \u0433\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u043d\u0438\u0436\u043d\u044f\u044f \u0433\u0440\u0430\u043d\u0438\u0446\u0430',
            },
        ),
        migrations.CreateModel(
            name='boundaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0413\u0440\u0430\u043d\u0438\u0446\u044b')),
            ],
            options={
                'db_table': 'boundaries_types',
                'verbose_name': '\u0413\u0440\u0430\u043d\u0438\u0446\u044b',
                'verbose_name_plural': '\u0413\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
        migrations.CreateModel(
            name='consistency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u043a\u043e\u043d\u0441\u0438\u0441\u0442\u0435\u043d\u0446\u0438\u044f')),
            ],
            options={
                'db_table': 'consistency_types',
                'verbose_name': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u043a\u043e\u043d\u0441\u0438\u0441\u0442\u0435\u043d\u0446\u0438\u044f',
                'verbose_name_plural': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u043a\u043e\u043d\u0441\u0438\u0441\u0442\u0435\u043d\u0446\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='flap_3_valve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043d\u0430 3-\u0445 \u0441\u0442\u0432\u043e\u0440\u0447\u0430\u0442\u043e\u043c \u043a\u043b\u0430\u043f\u0430\u043d\u0435')),
            ],
            options={
                'db_table': 'flap_3_valve_types',
                'verbose_name': '\u043d\u0430 3-\u0445 \u0441\u0442\u0432\u043e\u0440\u0447\u0430\u0442\u043e\u043c \u043a\u043b\u0430\u043f\u0430\u043d\u0435',
                'verbose_name_plural': '\u043d\u0430 3-\u0445 \u0441\u0442\u0432\u043e\u0440\u0447\u0430\u0442\u043e\u043c \u043a\u043b\u0430\u043f\u0430\u043d\u0435',
            },
        ),
        migrations.CreateModel(
            name='gallbladder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0416\u0435\u043b\u0447\u043d\u044b\u0439 \u043f\u0443\u0437\u044b\u0440\u044c')),
            ],
            options={
                'db_table': 'gallbladder_types',
                'verbose_name': '\u0416\u0435\u043b\u0447\u043d\u044b\u0439 \u043f\u0443\u0437\u044b\u0440\u044c',
                'verbose_name_plural': '\u0416\u0435\u043b\u0447\u043d\u044b\u0439 \u043f\u0443\u0437\u044b\u0440\u044c',
            },
        ),
        migrations.CreateModel(
            name='left_costal_arch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043d\u0438\u0436\u043d\u044f\u044f \u043f\u043e \u0441\u0440\u0435\u0434\u043d\u0435\u043a\u043b\u044e\u0447\u0438\u0447\u043d\u043e\u0439 \u043b\u0438\u043d\u0438\u0438')),
            ],
            options={
                'db_table': 'left_costal_arch_types',
                'verbose_name': '\u043b\u0435\u0432\u043e\u0439 \u0440\u0435\u0431\u0435\u0440\u043d\u043e\u0439 \u0434\u0443\u0433\u0435',
                'verbose_name_plural': '\u043b\u0435\u0432\u043e\u0439 \u0440\u0435\u0431\u0435\u0440\u043d\u043e\u0439 \u0434\u0443\u0433\u0435',
            },
        ),
        migrations.CreateModel(
            name='left_ebge_sternum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u043e \u043b\u0435\u0432\u043e\u043c\u0443 \u043a\u0440\u0430\u044e \u0433\u0440\u0443\u0434\u0438\u043d\u044b')),
            ],
            options={
                'db_table': 'left_ebge_sternum_types',
                'verbose_name': '\u041f\u043e \u043b\u0435\u0432\u043e\u043c\u0443 \u043a\u0440\u0430\u044e \u0433\u0440\u0443\u0434\u0438\u043d\u044b',
                'verbose_name_plural': '\u041f\u043e \u043b\u0435\u0432\u043e\u043c\u0443 \u043a\u0440\u0430\u044e \u0433\u0440\u0443\u0434\u0438\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='liver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u0435\u0447\u0435\u043d\u044c(\u041f\u043e \u041a\u0443\u0440\u043b\u043e\u0432\u0443)')),
            ],
            options={
                'db_table': 'liver_types',
                'verbose_name': '\u041f\u0435\u0447\u0435\u043d\u044c',
                'verbose_name_plural': '\u041f\u0435\u0447\u0435\u043d\u044c',
            },
        ),
        migrations.CreateModel(
            name='lower_midclavicularline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043d\u0438\u0436\u043d\u044f\u044f \u043f\u043e \u0441\u0440\u0435\u0434\u043d\u0435\u043a\u043b\u044e\u0447\u0438\u0447\u043d\u043e\u0439 \u043b\u0438\u043d\u0438\u0438')),
            ],
            options={
                'db_table': 'lower_midclavicularline_types',
                'verbose_name': '\u043d\u0438\u0436\u043d\u044f\u044f \u043f\u043e \u0441\u0440\u0435\u0434\u043d\u0435\u043a\u043b\u044e\u0447\u0438\u0447\u043d\u043e\u0439 \u043b\u0438\u043d\u0438\u0438',
                'verbose_name_plural': '\u043d\u0438\u0436\u043d\u044f\u044f \u043f\u043e \u0441\u0440\u0435\u0434\u043d\u0435\u043a\u043b\u044e\u0447\u0438\u0447\u043d\u043e\u0439 \u043b\u0438\u043d\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='on_palpation_edbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043a\u0440\u0430\u044f')),
            ],
            options={
                'db_table': 'on_palpation_edbe_types',
                'verbose_name': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043a\u0440\u0430\u044f',
                'verbose_name_plural': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043a\u0440\u0430\u044f',
            },
        ),
        migrations.CreateModel(
            name='oral_musosa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0421\u043b\u0438\u0437\u0438\u0441\u0442\u0430\u044f \u043f\u043e\u043b\u043e\u0441\u0430 \u0440\u0442\u0430')),
            ],
            options={
                'db_table': 'oral_musosa_types',
                'verbose_name': '\u0421\u043b\u0438\u0437\u0438\u0441\u0442\u0430\u044f \u043f\u043e\u043b\u043e\u0441\u0430 \u0440\u0442\u0430',
                'verbose_name_plural': '\u0421\u043b\u0438\u0437\u0438\u0441\u0442\u0430\u044f \u043f\u043e\u043b\u043e\u0441\u0430 \u0440\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='palpation_edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043a\u0440\u0430\u044f')),
            ],
            options={
                'db_table': 'palpation_edge_types',
                'verbose_name': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043a\u0440\u0430\u044f',
                'verbose_name_plural': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043a\u0440\u0430\u044f',
            },
        ),
        migrations.CreateModel(
            name='pancreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u043e\u0434\u0436\u0435\u043b\u0443\u0434\u043e\u0447\u043d\u0430\u044f \u0436\u0435\u043b\u0435\u0437\u0430')),
            ],
            options={
                'db_table': 'pancreas_types',
                'verbose_name': '\u041f\u043e\u0434\u0436\u0435\u043b\u0443\u0434\u043e\u0447\u043d\u0430\u044f \u0436\u0435\u043b\u0435\u0437\u0430',
                'verbose_name_plural': '\u041f\u043e\u0434\u0436\u0435\u043b\u0443\u0434\u043e\u0447\u043d\u0430\u044f \u0436\u0435\u043b\u0435\u0437\u0430',
            },
        ),
        migrations.CreateModel(
            name='pharynx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0417\u0435\u0432')),
            ],
            options={
                'db_table': 'pharynx_types',
                'verbose_name': '\u0417\u0435\u0432',
                'verbose_name_plural': '\u0417\u0435\u0432',
            },
        ),
        migrations.CreateModel(
            name='soreness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'db_table': 'soreness_types',
                'verbose_name': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438:  \u0431\u043e\u043b\u0435\u0437\u043d\u0435\u043d\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='spleen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0421\u0435\u043b\u0435\u0437\u0435\u043d\u043a\u0430')),
            ],
            options={
                'db_table': 'spleen_types',
                'verbose_name': '\u0421\u0435\u043b\u0435\u0437\u0435\u043d\u043a\u0430',
                'verbose_name_plural': '\u0421\u0435\u043b\u0435\u0437\u0435\u043d\u043a\u0430',
            },
        ),
        migrations.CreateModel(
            name='stomach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0416\u0438\u0432\u043e\u0442')),
            ],
            options={
                'db_table': 'stomach_types',
                'verbose_name': '\u0416\u0438\u0432\u043e\u0442',
                'verbose_name_plural': '\u0416\u0438\u0432\u043e\u0442',
            },
        ),
        migrations.CreateModel(
            name='surface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'db_table': 'surface_types',
                'verbose_name': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u043f\u0440\u0438 \u043f\u0430\u043b\u044c\u043f\u0430\u0446\u0438\u0438: \u043f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='teeth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0417\u0443\u0431\u044b')),
            ],
            options={
                'db_table': 'teeth_types',
                'verbose_name': '\u0417\u0443\u0431\u044b',
                'verbose_name_plural': '\u0417\u0443\u0431\u044b',
            },
        ),
        migrations.CreateModel(
            name='tongue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u042f\u0437\u044b\u043a')),
            ],
            options={
                'db_table': 'tongue_types',
                'verbose_name': '\u042f\u0437\u044b\u043a',
                'verbose_name_plural': '\u042f\u0437\u044b\u043a',
            },
        ),
        migrations.CreateModel(
            name='tonsils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041c\u0438\u043d\u0434\u0430\u043b\u0438\u043d\u044b')),
            ],
            options={
                'db_table': 'tonsils_types',
                'verbose_name': '\u041c\u0438\u043d\u0434\u0430\u043b\u0438\u043d\u044b',
                'verbose_name_plural': '\u041c\u0438\u043d\u0434\u0430\u043b\u0438\u043d\u044b',
            },
        ),
    ]
