# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadir', '0013_eye_symptoms_genitals_thyroid_gland_urinary_bladder'),
    ]

    operations = [
        migrations.CreateModel(
            name='consciousness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0421\u043e\u0437\u043d\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'consciousness_types',
                'verbose_name': '\u0421\u043e\u0437\u043d\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0421\u043e\u0437\u043d\u0430\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='dizziness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0413\u043e\u043b\u043e\u0432\u043e\u043a\u0440\u0443\u0436\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0413\u043e\u043b\u043e\u0432\u043e\u043a\u0440\u0443\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0413\u043e\u043b\u043e\u0432\u043e\u043a\u0440\u0443\u0436\u0435\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041b\u0438\u0446\u043e')),
            ],
            options={
                'verbose_name': '\u041b\u0438\u0446\u043e',
                'verbose_name_plural': '\u041b\u0438\u0446\u043e',
            },
        ),
        migrations.CreateModel(
            name='intellect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0418\u043d\u0442\u0435\u043b\u043b\u0435\u043a\u0442')),
            ],
            options={
                'verbose_name': '\u0418\u043d\u0442\u0435\u043b\u043b\u0435\u043a\u0442',
                'verbose_name_plural': '\u0418\u043d\u0442\u0435\u043b\u043b\u0435\u043a\u0442',
            },
        ),
        migrations.CreateModel(
            name='memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u0430\u043c\u044f\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u043c\u044f\u0442\u044c',
                'verbose_name_plural': '\u0418\u043d\u0442\u0435\u043b\u043b\u0435\u043a\u0442',
            },
        ),
        migrations.CreateModel(
            name='meningeal_symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041c\u0435\u043d\u0438\u043d\u0433\u0435\u0430\u043b\u044c\u043d\u044b\u0435 \u0421\u0438\u043c\u043f\u0442\u043e\u043c\u044b')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u043d\u0438\u043d\u0433\u0435\u0430\u043b\u044c\u043d\u044b\u0435 \u0421\u0438\u043c\u043f\u0442\u043e\u043c\u044b',
                'verbose_name_plural': '\u041c\u0435\u043d\u0438\u043d\u0433\u0435\u0430\u043b\u044c\u043d\u044b\u0435 \u0421\u0438\u043c\u043f\u0442\u043e\u043c\u044b',
            },
        ),
        migrations.CreateModel(
            name='movement_eyeballs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0414\u0432\u0438\u0436\u0435\u043d\u0438\u044f \u0433\u043b\u0430\u0437\u043d\u044b\u0445 \u044f\u0431\u043b\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u0414\u0432\u0438\u0436\u0435\u043d\u0438\u044f \u0433\u043b\u0430\u0437\u043d\u044b\u0445 \u044f\u0431\u043b\u043e\u043a',
                'verbose_name_plural': '\u0414\u0432\u0438\u0436\u0435\u043d\u0438\u044f \u0433\u043b\u0430\u0437\u043d\u044b\u0445 \u044f\u0431\u043b\u043e\u043a',
            },
        ),
        migrations.CreateModel(
            name='muscle_strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041c\u044b\u0448\u0435\u0447\u043d\u0430\u044f \u0441\u0438\u043b\u0430')),
            ],
            options={
                'verbose_name': '\u041c\u044b\u0448\u0435\u0447\u043d\u0430\u044f \u0441\u0438\u043b\u0430',
                'verbose_name_plural': '\u041c\u044b\u0448\u0435\u0447\u043d\u0430\u044f \u0441\u0438\u043b\u0430',
            },
        ),
        migrations.CreateModel(
            name='muscle_tone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041c\u044b\u0448\u0435\u0447\u043d\u044b\u0439 \u0442\u043e\u043d\u0443\u0441')),
            ],
            options={
                'verbose_name': '\u041c\u044b\u0448\u0435\u0447\u043d\u044b\u0439 \u0442\u043e\u043d\u0443\u0441',
                'verbose_name_plural': '\u041c\u044b\u0448\u0435\u0447\u043d\u044b\u0439 \u0442\u043e\u043d\u0443\u0441',
            },
        ),
        migrations.CreateModel(
            name='pathological_reflexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u0430\u0442\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0440\u0435\u0444\u043b\u0435\u043a\u0441\u044b')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u0442\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0440\u0435\u0444\u043b\u0435\u043a\u0441\u044b',
                'verbose_name_plural': '\u041f\u0430\u0442\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0440\u0435\u0444\u043b\u0435\u043a\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='protrude_tongue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u042f\u0437\u044b\u043a \u043f\u0440\u0438 \u0432\u044b\u0441\u043e\u0432\u044b\u0432\u0430\u043d\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u042f\u0437\u044b\u043a \u043f\u0440\u0438 \u0432\u044b\u0441\u043e\u0432\u044b\u0432\u0430\u043d\u0438\u0438',
                'verbose_name_plural': '\u042f\u0437\u044b\u043a \u043f\u0440\u0438 \u0432\u044b\u0441\u043e\u0432\u044b\u0432\u0430\u043d\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='pupils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0413\u043b\u0430\u0437\u043d\u044b\u0435 \u0441\u0438\u043c\u043f\u0442\u043e\u043c\u044b')),
            ],
            options={
                'verbose_name': '\u0413\u043b\u0430\u0437\u043d\u044b\u0435 \u0441\u0438\u043c\u043f\u0442\u043e\u043c\u044b',
                'verbose_name_plural': '\u0413\u043b\u0430\u0437\u043d\u044b\u0435 \u0441\u0438\u043c\u043f\u0442\u043e\u043c\u044b',
            },
        ),
        migrations.CreateModel(
            name='romberg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0412 \u043f\u043e\u0437\u0435 \u0420\u043e\u043c\u0431\u0435\u0440\u0433\u0430')),
            ],
            options={
                'verbose_name': '\u0412 \u043f\u043e\u0437\u0435 \u0420\u043e\u043c\u0431\u0435\u0440\u0433\u0430',
                'verbose_name_plural': '\u0412 \u043f\u043e\u0437\u0435 \u0420\u043e\u043c\u0431\u0435\u0440\u0433\u0430',
            },
        ),
        migrations.CreateModel(
            name='sensitivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0427\u0443\u0432\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u0427\u0443\u0432\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0427\u0443\u0432\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='suggestibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0412\u043d\u0443\u0448\u0430\u0435\u043c\u043e\u0441\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u0412\u043d\u0443\u0448\u0430\u0435\u043c\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0412\u043d\u0443\u0448\u0430\u0435\u043c\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='superficial_deepreflexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u043d\u044b\u0435 \u0438 \u0433\u043b\u0443\u0431\u043e\u043a\u0438\u0435 \u0440\u0435\u0444\u043b\u0435\u043a\u0441\u044b')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u043d\u044b\u0435 \u0438 \u0433\u043b\u0443\u0431\u043e\u043a\u0438\u0435 \u0440\u0435\u0444\u043b\u0435\u043a\u0441\u044b',
                'verbose_name_plural': '\u041f\u043e\u0432\u0435\u0440\u0445\u043d\u043e\u0441\u0442\u043d\u044b\u0435 \u0438 \u0433\u043b\u0443\u0431\u043e\u043a\u0438\u0435 \u0440\u0435\u0444\u043b\u0435\u043a\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='swallowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0413\u043b\u043e\u0442\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0413\u043b\u043e\u0442\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0413\u043b\u043e\u0442\u0430\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='symptom_Kerning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u0421\u0438\u043c\u043f\u0442\u043e\u043c \u041a\u0435\u0440\u043d\u0438\u043d\u0433')),
            ],
            options={
                'verbose_name': '\u0421\u0438\u043c\u043f\u0442\u043e\u043c \u041a\u0435\u0440\u043d\u0438\u043d\u0433',
                'verbose_name_plural': '\u0421\u0438\u043c\u043f\u0442\u043e\u043c \u041a\u0435\u0440\u043d\u0438\u043d\u0433',
            },
        ),
        migrations.CreateModel(
            name='valetudinarianism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='\u041c\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u041c\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u041c\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c',
            },
        ),
    ]
