# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadir', '0014_consciousness_dizziness_face_intellect_memory_meningeal_symptoms_movement_eyeballs_muscle_strength_m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupils',
            options={'verbose_name': '\u0417\u0440\u0430\u0447\u043a\u0438', 'verbose_name_plural': '\u0417\u0440\u0430\u0447\u043a\u0438'},
        ),
        migrations.AlterField(
            model_name='pupils',
            name='type',
            field=models.CharField(max_length=150, verbose_name='\u0417\u0440\u0430\u0447\u043a\u0438'),
        ),
    ]
